<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2023-exam</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="exam-2023_files/libs/clipboard/clipboard.min.js"></script>
<script src="exam-2023_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="exam-2023_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="exam-2023_files/libs/quarto-html/popper.min.js"></script>
<script src="exam-2023_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exam-2023_files/libs/quarto-html/anchor.min.js"></script>
<link href="exam-2023_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exam-2023_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exam-2023_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exam-2023_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exam-2023_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2023-exam</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="libraries" class="level6">
<h6 class="anchored" data-anchor-id="libraries">Libraries</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dataset" class="level6">
<h6 class="anchored" data-anchor-id="dataset">Dataset</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"DataExam2324.csv"</span>,<span class="at">header =</span> T,<span class="at">sep =</span> <span class="st">";"</span>,<span class="at">dec =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="remove-nas" class="level6">
<h6 class="anchored" data-anchor-id="remove-nas">Remove NAs</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exam-questions" class="level3">
<h3 class="anchored" data-anchor-id="exam-questions">Exam Questions</h3>
<section id="describe-the-250-patients-sample-defining-how-is-the-typical-patient-in-the-sample-and-main-features-of-the-distributions-for-relevant-variables-age-income-education-initial-bmipriorprograms" class="level4">
<h4 class="anchored" data-anchor-id="describe-the-250-patients-sample-defining-how-is-the-typical-patient-in-the-sample-and-main-features-of-the-distributions-for-relevant-variables-age-income-education-initial-bmipriorprograms">1. Describe the 250 patient’s sample defining how is the typical patient in the sample and main features of the distributions for relevant variables (age, income, education, initial BMI,Priorprograms…)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   InitialBMI      Education         Income           Age       
 Min.   :25.00   Min.   :1.000   Min.   :1.000   Min.   :20.00  
 1st Qu.:27.25   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:27.00  
 Median :30.00   Median :3.000   Median :3.000   Median :35.50  
 Mean   :29.83   Mean   :3.028   Mean   :3.048   Mean   :34.58  
 3rd Qu.:32.00   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:41.00  
 Max.   :35.00   Max.   :5.000   Max.   :5.000   Max.   :50.00  
 Priorprograms   Incomethousands Weeksintheprogram    Workouts    
 Min.   :0.000   Min.   :15.00   Min.   :1.000     Min.   :0.000  
 1st Qu.:0.000   1st Qu.:37.25   1st Qu.:3.000     1st Qu.:1.000  
 Median :0.000   Median :60.00   Median :5.000     Median :2.000  
 Mean   :0.472   Mean   :59.11   Mean   :4.844     Mean   :2.584  
 3rd Qu.:1.000   3rd Qu.:81.00   3rd Qu.:7.000     3rd Qu.:4.000  
 Max.   :1.000   Max.   :99.00   Max.   :8.000     Max.   :5.000  
     newbmi       Prescription     Weigthdiff      Recommendation 
 Min.   :19.24   Min.   :0.000   Min.   :-13.727   Min.   :0.000  
 1st Qu.:24.61   1st Qu.:0.000   1st Qu.:  1.337   1st Qu.:0.000  
 Median :27.26   Median :0.000   Median :  7.124   Median :0.000  
 Mean   :27.41   Mean   :0.416   Mean   :  6.978   Mean   :0.364  
 3rd Qu.:30.11   3rd Qu.:1.000   3rd Qu.: 12.391   3rd Qu.:1.000  
 Max.   :38.44   Max.   :1.000   Max.   : 24.478   Max.   :1.000  </code></pre>
</div>
</div>
<p>The typical (median) patient is a 35–36-year-old individual with an initial BMI of 30, a college education, and an annual income between $25,000 and $50,000. This person has not participated in previous programs, reports an income of $60,000 (suggesting a possible inconsistency between the Income and Incomethousand variables), stays in the program for 5 weeks, and exercises 2 hours per week. After the program, their BMI decreases to 27.26, corresponding to a weight loss of approximately 7.1 kg. The patient does not take any medication and would not recommend the program.</p>
<section id="age" class="level5">
<h5 class="anchored" data-anchor-id="age"><strong>Age</strong></h5>
<p>This is a discrete quantitative variable. Since it takes on many # different values, it can be effectively visualized using a histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Age)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">15</span>, <span class="at">fill=</span><span class="st">"steelblue"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"white"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"orange"</span>, <span class="at">alpha=</span><span class="fl">0.7</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Through the summary statistics, histogram, and boxplot, we can see that the minimum age is 20 and the maximum is 50. The ages are distributed quite heterogeneously, with some ages being more frequent than others and no clear pattern of uniformity. The data do not follow a normal distribution. From the boxplot, no outliers are observed, and the distribution appears to be slightly left-skewed (the mean is lower than the median).</p>
</section>
<section id="incomethousand" class="level5">
<h5 class="anchored" data-anchor-id="incomethousand"><strong>Incomethousand</strong></h5>
<p>quantitative cont. variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Incomethousands)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">15</span>, <span class="at">fill=</span><span class="st">"steelblue"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"white"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">y =</span> Incomethousands)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"orange"</span>, <span class="at">alpha=</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the summary statistics, histogram, and boxplot, we can observe that incomes are distributed in a roughly uniform manner, except for a few values. Incomes around $40,000 and $70,000 are less frequent, while the most common (modal) interval is surprisingly around $100,000. The overall distribution is fairly uniform and differs from a normal distribution. Nevertheless, it shows a good degree of symmetry (as seen in the boxplot) and no apparent outliers.</p>
</section>
<section id="education" class="level5">
<h5 class="anchored" data-anchor-id="education"><strong>Education</strong></h5>
<p>qualitative variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Education_class <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Education <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Basic"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Education <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"High School"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Education <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"College"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Education <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Master"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Education <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Doctorate"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Education_class)) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"Red"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Regarding education level, the most common category is College, while High School is the least common. Nevertheless, the frequencies across categories are fairly similar.</p>
</section>
<section id="initial-bmi" class="level5">
<h5 class="anchored" data-anchor-id="initial-bmi"><strong>Initial BMI</strong></h5>
<p>continuous quantitative variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> InitialBMI)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">fill=</span><span class="st">"steelblue"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"white"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">y =</span> InitialBMI)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"orange"</span>, <span class="at">alpha=</span><span class="fl">0.7</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Initial BMI values are fairly homogeneous, although their frequency tends to increase as BMI rises. Two noticeable peaks are observed around BMI values of 28 and 35. The minimum and maximum values are 25 and 35, respectively. The distribution appears to be slightly left-skewed, with no apparent outliers.</p>
</section>
<section id="prior-programs" class="level5">
<h5 class="anchored" data-anchor-id="prior-programs"><strong>Prior Programs</strong></h5>
<p>Categorical data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Priorprograms)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"Red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Approximately half of the sample has participated in previous programs, while the other half has not. However, those who have not participated in prior programs are slightly more numerous. According to the summary statistics (mean), 47.2% of participants have taken part in previous programs.</p>
</section>
</section>
<section id="give-ranges-for-mean-weight-loss-of-potential-patients-in-different-age-groups-and-different-income-categories." class="level4">
<h4 class="anchored" data-anchor-id="give-ranges-for-mean-weight-loss-of-potential-patients-in-different-age-groups-and-different-income-categories.">2. Give ranges for mean weight loss of potential patients in different age groups and different income categories.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create different age groups</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Age_groups <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">25</span> <span class="sc">~</span> <span class="st">"20-25"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&gt;</span> <span class="dv">25</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"25-30"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&gt;</span> <span class="dv">30</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"30-35"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&gt;</span> <span class="dv">35</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">40</span> <span class="sc">~</span> <span class="st">"35-40"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&gt;</span> <span class="dv">40</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">45</span> <span class="sc">~</span> <span class="st">"40-45"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>Age <span class="sc">&gt;</span> <span class="dv">45</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Age <span class="sc">&lt;=</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"45-50"</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># We can slightly modify the CI function to include it in summarise_at</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>CI_m_lower <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">ci =</span> <span class="fl">0.95</span>) {</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  standard_deviation <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  sample_size <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  Margin_Error <span class="ot">&lt;-</span>  <span class="fu">abs</span>(<span class="fu">qt</span>((<span class="dv">1</span><span class="sc">-</span>ci)<span class="sc">/</span><span class="dv">2</span>,<span class="at">df=</span>sample_size<span class="dv">-1</span>))<span class="sc">*</span> standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  lower <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> Margin_Error</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="at">lower =</span> lower)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>CI_m_upper <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">ci =</span> <span class="fl">0.95</span>) {</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  standard_deviation <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>  sample_size <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  Margin_Error <span class="ot">&lt;-</span>  <span class="fu">abs</span>(<span class="fu">qt</span>((<span class="dv">1</span><span class="sc">-</span>ci)<span class="sc">/</span><span class="dv">2</span>,<span class="at">df=</span>sample_size<span class="dv">-1</span>))<span class="sc">*</span> standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  upper <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">+</span> Margin_Error</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="at">upper =</span> upper)</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>df_grouped_byage <span class="ot">&lt;-</span> <span class="fu">group_by</span>(data,Age_groups)</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>df_summary_byage <span class="ot">&lt;-</span> df_grouped_byage <span class="sc">%&gt;%</span> </span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_at</span>(<span class="fu">vars</span>(Weigthdiff), </span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>               <span class="fu">list</span>(<span class="at">avg=</span>mean,<span class="at">median=</span>median,<span class="at">std=</span>sd,</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ci_l=</span>CI_m_lower,<span class="at">ci_u=</span>CI_m_upper))</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>df_summary_byage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  Age_groups    avg median   std   ci_l  ci_u
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 20-25      13.1   13.8    5.61 11.6   14.7 
2 25-30      10.4   11.2    5.50  8.54  12.2 
3 30-35       9.57   9.64   5.67  7.65  11.5 
4 35-40       4.35   4.62   5.62  2.83   5.87
5 40-45       1.95   1.31   6.25 -0.166  4.06
6 45-50       0.723  0.881  5.41 -1.16   2.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Age_groups, <span class="at">y =</span> Weigthdiff)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"lightblue"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As age increases, the expected amount of weight loss decreases (around 13–14 kilograms for younger participants compared to less than 1 kilogram for older ones. The standard deviation (i.e., the dispersion) remains fairly consistent across age groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_grouped_byincome <span class="ot">&lt;-</span> <span class="fu">group_by</span>(data,Income)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>df_summary_byincome <span class="ot">&lt;-</span> df_grouped_byincome <span class="sc">%&gt;%</span> <span class="co"># Mean and sd of var1 in each group</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_at</span>(<span class="fu">vars</span>(Weigthdiff), <span class="co"># You can add more variables!!!</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">list</span>(<span class="at">avg=</span>mean,<span class="at">median=</span>median,<span class="at">std=</span>sd,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ci_l=</span>CI_m_lower,<span class="at">ci_u=</span>CI_m_upper))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>df_summary_byincome</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  Income   avg median   std  ci_l  ci_u
   &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1      1  5.10   5.14  7.82  2.80  7.40
2      2  5.25   5.46  6.92  3.32  7.18
3      3  5.76   6.44  6.71  3.77  7.75
4      4  7.87   9.33  6.35  6.10  9.64
5      5 10.5   10.9   7.17  8.55 12.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(Income), <span class="at">y =</span> Weigthdiff)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"lightblue"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam-2023_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This time, the relationship appears to be the opposite: participants with higher incomes tend to experience greater weight loss. Although the difference among the first three income groups is almost negligible, for the highest earners, the weight loss can be nearly twice as large.</p>
</section>
<section id="talking-about-the-proportion-of-potential-recommendations-of-the-program-is-this-proportion-different-forhighly-educated-patients-master-and-doctorate" class="level4">
<h4 class="anchored" data-anchor-id="talking-about-the-proportion-of-potential-recommendations-of-the-program-is-this-proportion-different-forhighly-educated-patients-master-and-doctorate">3. Talking about the proportion of potential recommendations of the program, Is this proportion different forhighly educated patients (master and doctorate)?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>data_master <span class="ot">=</span> data[<span class="fu">which</span>(data<span class="sc">$</span>Education_class <span class="sc">==</span> <span class="st">"Master"</span>),]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>data_doctorate <span class="ot">=</span> data[<span class="fu">which</span>(data<span class="sc">$</span>Education_class <span class="sc">==</span> <span class="st">"Doctorate"</span>),]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>(<span class="at">prop_reccom_master =</span> <span class="fu">mean</span>(data_master<span class="sc">$</span>Recommendation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.48</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">prop_reccom_doctorate =</span> <span class="fu">mean</span>(data_doctorate<span class="sc">$</span>Recommendation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.42</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># At first glance, the proportions appear to differ. </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># But, is that difference statistically significant? Let’s find out.</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 1: Using confidence intervals</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>CI_p <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">ci =</span> <span class="dv">95</span>){</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">%&gt;%</span><span class="st">`</span> <span class="ot">&lt;-</span> magrittr<span class="sc">::</span><span class="st">`</span><span class="at">%&gt;%</span><span class="st">`</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  vcat<span class="ot">&lt;-</span><span class="fu">na.omit</span>(x)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  p<span class="ot">&lt;-</span><span class="fu">mean</span>(x)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  standard_deviation <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  sample_size <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  Margin_Error <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">qnorm</span>((<span class="dv">1</span><span class="sc">-</span>ci)<span class="sc">/</span><span class="dv">2</span>))<span class="sc">*</span> standard_deviation<span class="sc">/</span><span class="fu">sqrt</span>(sample_size)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  df_out <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">sample_size=</span><span class="fu">length</span>(x), p,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Margin_Error=</span>Margin_Error,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'CI lower limit'</span><span class="ot">=</span>(p <span class="sc">-</span> Margin_Error),</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'CI Upper limit'</span><span class="ot">=</span>(p <span class="sc">+</span> Margin_Error)) <span class="sc">%&gt;%</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"Measurements"</span>, <span class="at">values_to =</span><span class="st">"values"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span> )</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df_out)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">CI_p</span>(data_master<span class="sc">$</span>Recommendation, <span class="at">ci=</span><span class="fl">0.95</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Measurements   values
  &lt;chr&gt;           &lt;dbl&gt;
1 sample_size    50    
2 p               0.48 
3 Margin_Error    0.138
4 CI.lower.limit  0.342
5 CI.Upper.limit  0.618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">CI_p</span>(data_doctorate<span class="sc">$</span>Recommendation, <span class="at">ci=</span><span class="fl">0.95</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Measurements   values
  &lt;chr&gt;           &lt;dbl&gt;
1 sample_size    50    
2 p               0.42 
3 Margin_Error    0.137
4 CI.lower.limit  0.283
5 CI.Upper.limit  0.557</code></pre>
</div>
</div>
<p>We aim to test the following hypothesis:</p>
<ul>
<li><p>H0: p_master = p_doctorate</p></li>
<li><p>H1: p_master /= p_doctorate</p></li>
</ul>
<p>Using a 95% confidence interval, we find that the interval for Master’s graduates is (0.342, 0.618), while for Doctorate graduates it is (0.283, 0.557). Since the intervals overlap, although the recommendation proportions appear different in our sample, there may be no difference in the population as a whole. Therefore, we do not have sufficient evidence to reject H_0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 2: Using t-test:</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(data_master<span class="sc">$</span>Recommendation, data_doctorate<span class="sc">$</span>Recommendation, <span class="at">alternative =</span> <span class="st">"two.sided"</span>) <span class="co">#first step: test for equal variances</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  data_master$Recommendation and data_doctorate$Recommendation
F = 1.0246, num df = 49, denom df = 49, p-value = 0.9325
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.5814534 1.8055922
sample estimates:
ratio of variances 
          1.024631 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data_master<span class="sc">$</span>Recommendation, <span class="at">y=</span>data_doctorate<span class="sc">$</span>Recommendation, <span class="at">alternative=</span><span class="st">"two.sided"</span>, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  data_master$Recommendation and data_doctorate$Recommendation
t = 0.59805, df = 98, p-value = 0.5512
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.1390937  0.2590937
sample estimates:
mean of x mean of y 
     0.48      0.42 </code></pre>
</div>
</div>
<p>Since the p-value is 0.5512, for the usual significance levels (alpha = 0.01, 0.05, 0.1), we do not have sufficient evidence to reject H0.</p>
</section>
<section id="would-the-mean-bmi-for-potential-patients-decrease-significantly-during-the-program" class="level4">
<h4 class="anchored" data-anchor-id="would-the-mean-bmi-for-potential-patients-decrease-significantly-during-the-program">4. Would the mean BMI for potential patients decrease significantly during the program?</h4>
<p>Here, we want to test whether the program leads to a significant reduction in BMI, that is:</p>
<ul>
<li><p>H0: mu_BMI_prior &lt;= mu_BMI_post (Post-program BMI is greater than or equal to pre-program BMI = no weight loss)</p></li>
<li><p>H1: mu_BMI_prior &gt; mu_BMI_post. (Post-program BMI is lower than pre-program BMI = weight loss)</p></li>
</ul>
<p>In this case, the means are paired: for each individual, we have both the before and after measurements.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>InitialBMI, <span class="at">y=</span> data<span class="sc">$</span>newbmi, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  data$InitialBMI and data$newbmi
t = 15.208, df = 249, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is greater than 0
95 percent confidence interval:
 2.1524    Inf
sample estimates:
mean difference 
        2.41452 </code></pre>
</div>
</div>
<p>The p-value is effectively 0, providing strong evidence to reject H0. We can conclude that participation in the program leads to weight loss.</p>
</section>
<section id="would-the-potential-proportion-of-recommendations-vary-with-education-income-category-and-the-interaction-ofboth" class="level4">
<h4 class="anchored" data-anchor-id="would-the-potential-proportion-of-recommendations-vary-with-education-income-category-and-the-interaction-ofboth">5. Would the potential proportion of recommendations vary with education, income category and the interaction ofboth?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data_df_grouped_income_educ <span class="ot">&lt;-</span> <span class="fu">group_by</span>(data,Income,Education_class)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>data_df_summary_income_educ <span class="ot">&lt;-</span>data_df_grouped_income_educ <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_at</span>(<span class="fu">vars</span>(Recommendation),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">list</span>(<span class="at">avg=</span>mean,<span class="at">stde=</span>sd))</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>data_df_summary_income_educ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 4
# Groups:   Income [5]
   Income Education_class   avg  stde
    &lt;int&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt;
 1      1 Basic           0     0    
 2      1 College         0.182 0.405
 3      1 Doctorate       0.273 0.467
 4      1 High School     0.182 0.405
 5      1 Master          0.556 0.527
 6      2 Basic           0.222 0.428
 7      2 College         0.6   0.548
 8      2 Doctorate       0.5   0.535
 9      2 High School     0     0    
10      2 Master          0.333 0.5  
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>Overall, we can observe considerable variability in the proportion of recommendations, both across educational levels and income groups. The recommendation proportion ranges from 0 to 0.6. Let’s further examine the potential relationship using ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the analysis of variance</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>res.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Recommendation <span class="sc">~</span> Income<span class="sc">*</span>Education_class, <span class="at">data =</span> data)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the analysis</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res.aov) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Df Sum Sq Mean Sq F value  Pr(&gt;F)    
Income                   1   2.96  2.9646  13.672 0.00027 ***
Education_class          4   2.39  0.5968   2.752 0.02879 *  
Income:Education_class   4   0.48  0.1212   0.559 0.69271    
Residuals              240  52.04  0.2168                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We can observe that, at a significance level of alpha = 0.05, both income and education level are relevant factors for studying the proportion of recommendations. In contrast, their interaction does not appear to be a significant factor.</p>
</section>
<section id="could-you-say-if-there-is-a-relation-between-the-potential-recommendation-of-the-program-and-the-prior-enrollmentof-the-patient-in-other-weight-loss-programs" class="level4">
<h4 class="anchored" data-anchor-id="could-you-say-if-there-is-a-relation-between-the-potential-recommendation-of-the-program-and-the-prior-enrollmentof-the-patient-in-other-weight-loss-programs">6. Could you say if there is a relation between the potential recommendation of the program and the prior enrollmentof the patient in other weight loss programs?</h4>
<p>Here, we are asked about a possible non-monotonic association (presence/absence) between recommendation and prior enrollment in other programs. We can construct a contingency table to check whether a dependency exists.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We create the contingency table.</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ConTab<span class="ot">=</span> <span class="fu">table</span>(<span class="st">"Reccom"</span><span class="ot">=</span>data<span class="sc">$</span>Recommendation,<span class="st">"Prior"</span><span class="ot">=</span>data<span class="sc">$</span>Priorprograms)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We create a table of relative frequencies conditioned on prior program participation.</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(ConTab,<span class="at">margin =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Prior
Reccom         0         1
     0 0.6136364 0.6610169
     1 0.3863636 0.3389831</code></pre>
</div>
</div>
<p>We can observe that there is no strong relationship between prior program participation and giving a recommendation. However, those who have previously participated in a program tend to recommend it slightly more, although the difference is very small. We check it using the Chi-squared test of independence:</p>
<ul>
<li><p>H0: the variables are independent</p></li>
<li><p>H1: there is a dependency relationship</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(ConTab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  ConTab
X-squared = 0.41684, df = 1, p-value = 0.5185</code></pre>
</div>
</div>
<p>Since the p-value is 0.5185, we do not have sufficient evidence to reject H0; there is no relationship between Recommendation and Priorprograms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cramersV</span>(ConTab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04083318</code></pre>
</div>
</div>
<p>The Cramér’s V value is very low (0.0408), indicating a very weak association.</p>
</section>
<section id="find-a-predictive-procedure-able-to-give-the-expected-weight-loss-during-the-program-as-a-function-of-relevantinformation-on-the-patient." class="level4">
<h4 class="anchored" data-anchor-id="find-a-predictive-procedure-able-to-give-the-expected-weight-loss-during-the-program-as-a-function-of-relevantinformation-on-the-patient.">7. Find a predictive procedure able to give the expected weight loss during the program as a function of relevantinformation on the patient.</h4>
<p>Here, we are asked to develop a predictive model for weight loss (Weigthdiff). We will build a multiple linear regression model and aim to identify the best possible model. To avoid multicollinearity issues, we remove variables that are redundant:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Education <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Income <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Age_groups <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We start by building a model with all explanatory variables.</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">lm</span>(Weigthdiff<span class="sc">~</span>. , <span class="at">data =</span> data)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weigthdiff ~ ., data = data)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.430e-12 -1.178e-14  5.720e-15  2.098e-14  1.904e-13 

Coefficients:
                             Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept)                 2.252e-14  7.774e-14  2.900e-01   0.7723    
InitialBMI                  2.890e+00  8.953e-15  3.228e+14   &lt;2e-16 ***
Age                        -2.812e-15  1.439e-15 -1.954e+00   0.0519 .  
Priorprograms              -1.535e-14  1.399e-14 -1.097e+00   0.2736    
Incomethousands            -1.418e-16  2.529e-16 -5.610e-01   0.5755    
Weeksintheprogram           3.383e-15  4.667e-15  7.250e-01   0.4692    
Workouts                    9.144e-15  6.253e-15  1.462e+00   0.1450    
newbmi                     -2.890e+00  8.585e-15 -3.366e+14   &lt;2e-16 ***
Prescription               -1.445e-14  1.265e-14 -1.142e+00   0.2545    
Recommendation             -3.076e-14  2.166e-14 -1.420e+00   0.1569    
Education_classCollege     -1.038e-14  2.087e-14 -4.970e-01   0.6194    
Education_classDoctorate    1.223e-14  2.486e-14  4.920e-01   0.6234    
Education_classHigh School -1.560e-15  2.042e-14 -7.600e-02   0.9392    
Education_classMaster       1.285e-14  2.221e-14  5.780e-01   0.5635    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.681e-14 on 236 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 1.076e+29 on 13 and 236 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We see that only InitialBMI, Age, newbmi, and WeightDiff are relevant. </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We select these variables.</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">=</span> <span class="fu">lm</span>(Weigthdiff<span class="sc">~</span>. , <span class="at">data =</span> data[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">7</span>,<span class="dv">9</span>)])</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weigthdiff ~ ., data = data[, c(1, 2, 7, 9)])

Residuals:
       Min         1Q     Median         3Q        Max 
-1.479e-12 -4.430e-15  6.020e-15  1.611e-14  1.930e-13 

Coefficients:
              Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept) -5.242e-14  7.040e-14 -7.450e-01    0.457    
InitialBMI   2.890e+00  3.596e-15  8.038e+14   &lt;2e-16 ***
Age         -1.247e-15  8.833e-16 -1.412e+00    0.159    
newbmi      -2.890e+00  3.111e-15 -9.290e+14   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.633e-14 on 246 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.708e+29 on 3 and 246 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We see that Age is not relevant in this new model, so we remove it.</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>model_3 <span class="ot">=</span> <span class="fu">lm</span>(Weigthdiff<span class="sc">~</span>. , <span class="at">data =</span> data[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">7</span>,<span class="dv">9</span>)])</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weigthdiff ~ ., data = data[, c(1, 7, 9)])

Residuals:
       Min         1Q     Median         3Q        Max 
-1.499e-12 -3.440e-15  6.140e-15  1.437e-14  1.876e-13 

Coefficients:
              Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept) -8.118e-14  6.217e-14 -1.306e+00    0.193    
InitialBMI   2.890e+00  3.085e-15  9.367e+14   &lt;2e-16 ***
newbmi      -2.890e+00  2.460e-15 -1.175e+15   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.71e-14 on 247 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 6.95e+29 on 2 and 247 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We obtain a model that can predict weight loss using both the old and new BMI, but this is trivial. Naturally, knowing this difference makes it obvious what the weight loss is, since BMI = weight / height^2. Assuming the person’s height remains constant, the difference in BMI is: (old weight - current weight) / height^2 = WeightDiff / height^2, so WeightDiff = height^2 * old BMI - height^2 * new BMI.</p>
<p>Therefore, we will assume we are at the beginning of the program, knowing all the information except the new BMI, in order to predict the expected weight loss.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>model_4 <span class="ot">=</span> <span class="fu">lm</span>(Weigthdiff<span class="sc">~</span>. , <span class="at">data =</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">7</span>)])</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weigthdiff ~ ., data = data[, -c(7)])

Residuals:
    Min      1Q  Median      3Q     Max 
-4.9085 -1.3993 -0.0908  1.3965  5.4360 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 9.052267   1.594964   5.676 4.02e-08 ***
InitialBMI                 -0.040421   0.045785  -0.883   0.3782    
Age                        -0.391521   0.018530 -21.129  &lt; 2e-16 ***
Priorprograms              -1.980367   0.277550  -7.135 1.17e-11 ***
Incomethousands             0.006308   0.005515   1.144   0.2538    
Weeksintheprogram           1.162937   0.068614  16.949  &lt; 2e-16 ***
Workouts                    1.552847   0.092328  16.819  &lt; 2e-16 ***
Prescription                0.061779   0.276696   0.223   0.8235    
Recommendation              3.077013   0.429369   7.166 9.70e-12 ***
Education_classCollege      2.754448   0.419781   6.562 3.32e-10 ***
Education_classDoctorate    4.965282   0.437704  11.344  &lt; 2e-16 ***
Education_classHigh School  1.058840   0.441125   2.400   0.0172 *  
Education_classMaster       3.206848   0.438625   7.311 4.05e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.117 on 237 degrees of freedom
Multiple R-squared:  0.9189,    Adjusted R-squared:  0.9148 
F-statistic: 223.9 on 12 and 237 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that, at alpha = 0.05, InitialBMI, Incomethousands, and Prescription are no longer relevant, so we remove them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>model_5 <span class="ot">=</span> <span class="fu">lm</span>(Weigthdiff<span class="sc">~</span>. , <span class="at">data =</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">8</span>)])</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weigthdiff ~ ., data = data[, -c(1, 4, 7, 8)])

Residuals:
    Min      1Q  Median      3Q     Max 
-4.9749 -1.4083 -0.0485  1.4175  5.5790 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 8.25906    0.76920  10.737  &lt; 2e-16 ***
Age                        -0.39281    0.01841 -21.340  &lt; 2e-16 ***
Priorprograms              -1.94773    0.27512  -7.079 1.59e-11 ***
Weeksintheprogram           1.17358    0.06722  17.460  &lt; 2e-16 ***
Workouts                    1.55388    0.09198  16.894  &lt; 2e-16 ***
Recommendation              3.01158    0.42632   7.064 1.74e-11 ***
Education_classCollege      2.76443    0.41823   6.610 2.47e-10 ***
Education_classDoctorate    4.95260    0.43631  11.351  &lt; 2e-16 ***
Education_classHigh School  0.99916    0.43826   2.280   0.0235 *  
Education_classMaster       3.18586    0.43718   7.287 4.54e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.114 on 240 degrees of freedom
Multiple R-squared:  0.9182,    Adjusted R-squared:  0.9151 
F-statistic: 299.3 on 9 and 240 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We obtain a model with R^2 = 0.9182, explaining 91.82% of the variability in our variable of interest.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>