---
title: "Homepage"
format: html
editor: visual
---

## Resources

-   [Execution Options](https://quarto.org/docs/computations/execution-options.html)
-   [dplyr cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/dplyr.pdf)
-   [forcats cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/forcats.pdf)
-   [ggplot2 cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/ggplot2.pdf)
-   [lubridate cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/lubridate.pdf)
-   [purrr cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/purrr.pdf)
-   [readr cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/readr.pdf)
-   [stringr cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/stringr.pdf)
-   [tidyr cheatsheet](https://uc3mamelia.github.io/data_programming_notes/Cheatsheets/tidyr.pdf)

## Data Programming Notes

-   [libraries, data types, dates, basic operators, logic, add elements, delete elements, glue, extract, data tables, tibble](https://uc3mamelia.github.io/data_programming_notes/study_sheet.html)

-   [nrow, ncol, order(), unique(), mean(), sd()](https://uc3mamelia.github.io/data_programming_notes/case_study_mock_task.html)

-   [tidy data, pivot_longer, pivot_wider](https://uc3mamelia.github.io/data_programming_notes/sept_11_class.html)

-   [separate, unite, pivot_longer with extra specs, sampling](https://uc3mamelia.github.io/data_programming_notes/sept_18_class.html)

-   [remove NAs](https://uc3mamelia.github.io/data_programming_notes/sept_28_class.html)

-   [column functions: select, unselect, rename, relocate, mutate, flow structures](https://uc3mamelia.github.io/data_programming_notes/oct_2_class.html)

-   [if_else, summarize(), case_when](https://uc3mamelia.github.io/data_programming_notes/oct-9.html)

-   [summarize, slice_max, stratified sample, slice sample, change graph color](https://uc3mamelia.github.io/data_programming_notes/oct-16.html)

-   [Joins](https://uc3mamelia.github.io/data_programming_notes/oct-23.html)

-   [imports and exports](https://uc3mamelia.github.io/data_programming_notes/nov-4.html)

## Statistics Notes

#### [Descriptive Statistics](https://uc3mamelia.github.io/data_programming_notes/descriptive-stats.html)

-   types of variables, univariate descriptive analysis, measures of variability, measures of central tendency, frequency tables, bivariate descriptive analysis

#### [Inferential Statistics](https://uc3mamelia.github.io/data_programming_notes/inferential-stats.html)

-   point estimators, create a sample from an existing population, confidence intervals, hypothesis testing, z-test, t-test, Chi-squared test, paired t-test, independent t-test, ANOVA

#### [Associative Statistics](https://uc3mamelia.github.io/data_programming_notes/associative-stats.html)

-   associative analysis, volume plots, correlograms, matrix of scatterplots, simple linear regression, residuals, coefficients, multiple linear regression, ANOVA for every variable

## Stats II Notes

-   [Exploratory Data Analysis](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/Data_explorer_example.html)

-   [Determining Correlation](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/determining_correlation.html)

-   [Hypothesis Testing](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/hypothesis_testing.html)

-   [Linear Regression](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/linear_regression.html)

-   [Logistic Regression](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/logistic_regression.html)

-   [Regularization - Caret](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/regularization_caret.html)

-   [Regularization - GLM Net](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/regularization_glmnet.html)

-   [Multinomial Classification](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/multinomial_classification.html)

-   [Poisson Regression](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/poisson_regression.html)

-   [Regularized GLMs](https://uc3mamelia.github.io/data_programming_notes/statistics-ii/regulairzed_glms.html)

## Data Visualization Notes

#### [Building Graphs Layer by Layer](https://uc3mamelia.github.io/data_programming_notes/data-viz-1.html)

-   ggplot, aes, geom_point, geom_line, geom_histogram, color, fill, facet_wrap

#### [Scales and Guides](https://uc3mamelia.github.io/data_programming_notes/data-viz-2.html)

-   scale_x_continuous, scale_y_continuous, scale_color_discrete(), labs, range(), lims(), breaks, guides, transformations

#### [Coordinate Systems](https://uc3mamelia.github.io/data_programming_notes/data-viz-3.html)

-   coordinate systems, coord_cartesian(), coord_flip(), coord_fixed(), pie charts, clipping, transformations, maps

#### [Faceting](https://uc3mamelia.github.io/data_programming_notes/data-viz-4.html)

-   facet_grid, facet_wrap, controlling scales, missing faceting values

#### [Themes](https://uc3mamelia.github.io/data_programming_notes/data-viz-5.html)

-   predefined themes, built-in themes, modifying themes, modifying text elements, modifying line elements, modifying borders, plot elements, axis elements, legend elements, panel elements, faceting elements, exporting (DPI)

#### [Annotations](https://uc3mamelia.github.io/data_programming_notes/data-viz-6.html)

-   titles, subtitles, guides, text labels, highlighting points, reference lines, reference areas, individual annotations (segments), spatial coordinates, direct labeling, annotating groups of points, gghighlight

#### [Arranging Plots](https://uc3mamelia.github.io/data_programming_notes/data-viz-7.html)

## Text Mining

-   [Breaking the Ice](https://uc3mamelia.github.io/data_programming_notes/text-mining/0---Breaking-the-ice_SOLVED.html)

-   [Working with Multiple Texts](https://uc3mamelia.github.io/data_programming_notes/text-mining/1---Working-with-multiple-texts.html)

-   [Sentiment Analysis](https://uc3mamelia.github.io/data_programming_notes/text-mining/2---Sentiment-analysis_SOLVED.html)

-   [Term Frequency](https://uc3mamelia.github.io/data_programming_notes/text-mining/3---Term-frequency_SOLVED.html)

-   [Lemmatize](https://uc3mamelia.github.io/data_programming_notes/text-mining/lemmatize.html)

-   [N Grams](https://uc3mamelia.github.io/data_programming_notes/text-mining/4---N-grams.html)

## Survey

-   [Why Surveys](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Why%20Surveys.html)

-   [Socio-demographic variables in surveys](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Socio-demographic%20variables%20in%20surveys.html)

-   [Missing Data](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Missing_data.html)

-   [Paradata](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Paradata.html#/title-slide)

-   [Class Imbalance Data](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Dealing%20with%20class%20imbalance.html)

-   [Stargazer Example](https://uc3mamelia.github.io/data_programming_notes/survey-ii/Stargazer_example.html)

-   [Survey Experiments](https://uc3mamelia.github.io/data_programming_notes/survey-ii/survey-experiments.html)

## Data Harvesting

-   [A primer on Webscraping](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-1.html)

-   [Regular Expressions](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-2.html)

-   [Case Study: Scraping Spanish Schools in Spain](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-3.html)

-   [Scraping Javascript based website](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-4.html)

-   [APIs](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-5.html)

-   [Introduction to JSON](https://uc3mamelia.github.io/data_programming_notes/data-harvesting/data-harvesting-6.html)

## Advanced Modeling

-   [Featuring Engineering](https://uc3mamelia.github.io/data_programming_notes/advanced-modeling/1.1-national-elections.html)

-   [PCA](https://uc3mamelia.github.io/data_programming_notes/advanced-modeling/2.1-socioeconomic-PCA.html)

-   [Clustering](https://uc3mamelia.github.io/data_programming_notes/advanced-modeling/2.2-socioeconomic-clustering.html)

-   [Probabilistic Learning](https://uc3mamelia.github.io/data_programming_notes/advanced-modeling/3.1-probabilistic-learning-and-knn.html)

## Retired

#### [Happiness Stats](https://uc3mamelia.github.io/data_programming_notes/happiness_quarto.html)

-   Univariate descriptive analysis, bivariate descriptive analysis, confidence intervals

#### [Seniors Stats](https://uc3mamelia.github.io/data_programming_notes/seniors.html)

-   Univariate descriptive analysis, bivariate descriptive analysis, confidence intervals

## Assignments

#### Data Programming

-   [Task 0 - Intro to R Exam](https://uc3mamelia.github.io/data_programming_notes/task-0.html)

-   First Data Programming Assignment

#### Stats

-   [2023-2024 Exam](https://uc3mamelia.github.io/data_programming_notes/exam-2023.html)

-   First Stats I Assignment

-   [Second Stats I Assignment](https://uc3mamelia.github.io/data_programming_notes/second_assignment_amelia_shuler.html)

-   Stats I Exam

-   Third Stats I Assignment
