<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amelia Shuler">

<title>Stats Assignment 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="stats-3_files/libs/clipboard/clipboard.min.js"></script>
<script src="stats-3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="stats-3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="stats-3_files/libs/quarto-html/popper.min.js"></script>
<script src="stats-3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stats-3_files/libs/quarto-html/anchor.min.js"></script>
<link href="stats-3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stats-3_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stats-3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stats-3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stats-3_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stats Assignment 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Amelia Shuler </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="libraries" class="level6">
<h6 class="anchored" data-anchor-id="libraries">Libraries</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dbplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots) <span class="co"># For balloonplot</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr) <span class="co"># For Cramers'V</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PerformanceAnalytics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-and-refine-data" class="level6">
<h6 class="anchored" data-anchor-id="import-and-refine-data">Import and Refine Data</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"~/Desktop/stats-3/sgdata.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># edit population sex data from 0 and 1</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> population <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">str_replace</span>(Sex, <span class="st">"0"</span>, <span class="st">"female"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">str_replace</span>(Sex, <span class="st">"1"</span>, <span class="st">"male"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the age_range variable</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> population <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"age_range"</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"under 10"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"11-20"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"21-30"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">40</span> <span class="sc">~</span> <span class="st">"31-40"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"41-50"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">60</span> <span class="sc">~</span> <span class="st">"51-60"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">70</span> <span class="sc">~</span> <span class="st">"61-70"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&lt;=</span> <span class="dv">80</span> <span class="sc">~</span> <span class="st">"71-80"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">&gt;</span> <span class="dv">80</span> <span class="sc">~</span> <span class="st">"81-+"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="qualitative-analysis" class="level3">
<h3 class="anchored" data-anchor-id="qualitative-analysis">Qualitative Analysis</h3>
<p>Sex, martial status, education, and occupation are all categorical values. We will conduct a chi-squared test on those.</p>
<p><u>Sex and Education</u></p>
<p>Is sex proportional to education?</p>
<p>H0: sex and education proportions are equal.</p>
<p>H1: sex and education proportions are not equal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Contingency table for sex and education</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ConTtable <span class="ot">&lt;-</span> <span class="fu">table</span>(population<span class="sc">$</span>Sex, population<span class="sc">$</span>Education)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>RConTtable<span class="ot">&lt;-</span><span class="fu">prop.table</span>(ConTtable)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Graphical visualization of the table.</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">balloonplot</span>(<span class="fu">t</span>(RConTtable), <span class="at">main =</span><span class="st">"Sex"</span>, <span class="at">xlab =</span><span class="st">""</span>, <span class="at">ylab=</span><span class="st">""</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>, <span class="at">show.margins =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Visually, we can see that high school has larger dots across both males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chi square test</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(population<span class="sc">$</span>Sex, <span class="at">y =</span> population<span class="sc">$</span>Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  population$Sex and population$Education
X-squared = 174.53, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The chi-square test tells us that the p-value (&lt;2.2e-16) is super low, meaning that can reject the null hypothesis and say that Sex and Education proportions are not equal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cramers V</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramersV</span>(ConTtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2954046</code></pre>
</div>
</div>
<p>The Cramer’s V test tells us that Sex and Education have a moderate relationship, of 0.295.</p>
<p><u>Sex and Occupation</u></p>
<p>Is sex proportional to occupation?</p>
<p>H0: sex and occupation are proportional.</p>
<p>H1: sex and occupation are not proportional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Contingency table for sex and occupation</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ConTtable <span class="ot">&lt;-</span> <span class="fu">table</span>(population<span class="sc">$</span>Sex, population<span class="sc">$</span>Occupation)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>RConTtable<span class="ot">&lt;-</span><span class="fu">prop.table</span>(ConTtable)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Graphical visualization of the table.</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">balloonplot</span>(<span class="fu">t</span>(RConTtable), <span class="at">main =</span><span class="st">"Sex"</span>, <span class="at">xlab =</span><span class="st">""</span>, <span class="at">ylab=</span><span class="st">""</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>, <span class="at">show.margins =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(population<span class="sc">$</span>Occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "skilled employee / official"                                     
[2] "unemployed / unskilled"                                          
[3] "management / self-employed / highly qualified employee / officer"</code></pre>
</div>
</div>
<p>Visually, we can see that skilled employee / official has larger dots for both males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chi square test</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(population<span class="sc">$</span>Sex, <span class="at">y =</span> population<span class="sc">$</span>Occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  population$Sex and population$Occupation
X-squared = 84.56, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The chi-square test tells us that the p-value (&lt;2.2e-16) is super low, meaning that we can reject the null hypothesis and say that Sex and Occupation are not proportional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cramers V</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramersV</span>(ConTtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2056209</code></pre>
</div>
</div>
<p>The Cramer’s V test tells us that Sex and Education have a moderate relationship, of 0.206.</p>
<p><u>Education and Occupation</u></p>
<p>Is Education proportional to Occupation?</p>
<p>H0: Education and occupation are proportional.</p>
<p>H1: Education and occupation are not proportional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Contingency table for education and occupation</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ConTtable <span class="ot">&lt;-</span> <span class="fu">table</span>(population<span class="sc">$</span>Education, population<span class="sc">$</span>Occupation)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>RConTtable<span class="ot">&lt;-</span><span class="fu">prop.table</span>(ConTtable)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Graphical visualization of the table.</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">balloonplot</span>(<span class="fu">t</span>(RConTtable), <span class="at">main =</span><span class="st">"Education"</span>, <span class="at">xlab =</span><span class="st">""</span>, <span class="at">ylab=</span><span class="st">""</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>, <span class="at">show.margins =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(population<span class="sc">$</span>Occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "skilled employee / official"                                     
[2] "unemployed / unskilled"                                          
[3] "management / self-employed / highly qualified employee / officer"</code></pre>
</div>
</div>
<p>Visually, we can see that high school education has the largest dots for all occupations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chi square test</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(population<span class="sc">$</span>Education, <span class="at">y =</span> population<span class="sc">$</span>Occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(population$Education, y = population$Occupation):
Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  population$Education and population$Occupation
X-squared = 39.116, df = 6, p-value = 6.793e-07</code></pre>
</div>
</div>
<p>The chi-square test tells us that the p-value (6.793e-07) is super high, meaning that we can accept the null hypothesis and say that Education and Occupation are proportional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cramers V</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramersV</span>(ConTtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in stats::chisq.test(...): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09888859</code></pre>
</div>
</div>
<p>The Cramer’s V test also tells us the variables are not related, since the value is close to zero (0.1).</p>
</section>
<section id="quantitative-analysis" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-analysis">Quantitative Analysis</h3>
<p>Age and Income are quantitative variables. We will run a linear regression on them.</p>
<p><u>Age and Income</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data.dfB<span class="ot">&lt;-</span><span class="fu">data.frame</span>(population<span class="sc">$</span>Age, population<span class="sc">$</span>Income)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation matrix</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">cor</span>(data.dfB),<span class="dv">2</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co">#correlation matrix with p-values</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>res2 <span class="ot">&lt;-</span> <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(data.dfB))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>res2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  population.Age population.Income
population.Age              1.00              0.34
population.Income           0.34              1.00

n= 2000 


P
                  population.Age population.Income
population.Age                    0               
population.Income  0                              </code></pre>
</div>
</div>
<p>Before using the correlation matrix plot, I’ve checked to see if the variables have a relationship before modeling and check for multi-collinearity. The first four points are the correlation coefficient: we can see that there is a moderate positive linear relationship (0.34) between age and income. The p-value is 0, meaning that the results are highly statistically significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Visualization of the data matrix</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(res, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">order =</span> <span class="st">"hclust"</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also see in the plot that age and income have larger / darker dots indicating a stronger, positive correlation.</p>
<p>Because we have two variables with a strong linear correlation, let’s use a simple linear regression to look at age’s affect on income.</p>
<p>H_0: Age does not predict Income.</p>
<p>H_1: Age predicts income.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(population, <span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">y=</span>Income)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(population<span class="sc">$</span>Income <span class="sc">~</span> population<span class="sc">$</span>Age) <span class="co"># linear model function</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model) <span class="co"># returns residuals, coefficients, etc</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = population$Income ~ population$Age)

Residuals:
   Min     1Q Median     3Q    Max 
-89110 -21088  -3843  16531 191866 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     81182.1     2583.5   31.42   &lt;2e-16 ***
population$Age   1107.6       68.4   16.19   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 35840 on 1998 degrees of freedom
Multiple R-squared:  0.116, Adjusted R-squared:  0.1156 
F-statistic: 262.2 on 1 and 1998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>population <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min"</span> <span class="ot">=</span> <span class="fu">min</span>(Age)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  min
1  18</code></pre>
</div>
</div>
<p>The p-value is &lt;2e-16 for both variables, meaning we reject the null hypothesis and accept that age predicts income.</p>
<p>When age is zero, Income is 81,182.10 USD, which here is not relevant because minimum age is 18 (and realistically people are not born earning money).</p>
<p>For every 1 unit increase in Age, Income increases by 1,107.60 USD.</p>
<p>Older individuals in this population tend to earn higher incomes, but the relationship is not very strong. Other factors (e.g., education, occupation, experience) likely also play major roles in explaining income differences.</p>
<p>The multiple R-squared is 0.116, meaning 11.6% of the variation in income is explained by age. This suggests a weak linear relationship.</p>
<p>Let’s try to predict future values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>predicted_income <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> population)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These are the predictions for every observation in the population. Let’s compare them to the actual incomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> population)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">=</span> population<span class="sc">$</span>Income <span class="sc">-</span> yhat</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1            2            3            4            5            6 
-30720.39404  45224.00305 -46243.83521  40541.51120   9146.81839  24900.37722 
           7            8            9           10           11           12 
 16610.81839  73673.37722   2846.12557  62451.48343   -402.75676  19831.82984 
          13           14           15           16           17           18 
  3138.00305 -58263.28783  -9295.51657 -28196.86297 -14334.18161  48562.24324 
          19           20           21           22           23           24 
132036.09780  29139.72363 -15569.24860  17595.09780 -44542.24860   5002.09780 
          25           26           27           28           29           30 
 -6312.34336 -49146.20938 -56113.96919  35324.27101    466.96382  24921.95237 
          31           32           33           34           35           36 
 38590.79062   9044.07004  48335.31023 -56709.52802  37836.55042  -4366.75676 
          37           38           39           40           41           42 
 27867.72363   5513.20402  -2886.79598 -15222.17016  48919.31023  20941.65664 
          43           44           45           46           47           48 
  3742.09780  47339.82984  -3087.11462  18439.37722  15804.03081 -41235.58356 
          49           50           51           52           53           54 
  6122.03081  10636.48343 -28771.10317  65786.31023 -16813.75676   1640.72363 
          55           56           57           58           59           60 
 -8484.52802 -51721.34336  63798.40499  68139.72363  45610.41644   8583.41644 
          61           62           63           64           65           66 
 -4131.92996 -12920.42181  17665.12557 118513.24324   8392.65664  13768.75140 
          67           68           69           70           71           72 
 -2233.10317  34231.00305 -15184.79598   1147.24324  54692.31023 -58428.07540 
          73           74           75           76           77           78 
  4188.99159   9365.85761  15402.44421   3016.19256   6346.96382  17816.99159 
          79           80           81           82           83           84 
 27319.03081  20851.00305  29330.09780   2899.33800 -22972.17016 -45212.11462 
          85           86           87           88           89           90 
-45070.59501  20480.89683  -1022.92996 107829.33800  34612.31023 -19221.51657 
          91           92           93           94           95           96 
-32601.94142 -24387.76821 -46662.44958  25344.17625  24238.23179 122917.88538 
          97           98           99          100          101          102 
-13674.87443  15953.96382   -902.20938  74409.79062 -33221.14239   2681.82984 
         103          104          105          106          107          108 
-12578.17016  -4604.62278  -2703.34336 120338.03081  58730.03081  36251.13703 
         109          110          111          112          113          114 
 50737.31023  20572.37722   8685.72363    548.41644   9237.48343  53573.24324 
         115          116          117          118          119          120 
 14164.37722  -1396.66200  75486.31023  -1987.92996  46882.41644  59439.79062 
         121          122          123          124          125          126 
 -4218.75676  40339.85761 -41646.17016 -15206.04763   5016.07004 -10116.68977 
         127          128          129          130          131          132 
-53783.55579 -15343.68977  25138.96382  10515.89683  68949.82984  35946.89683 
         133          134          135          136          137          138 
-33551.92996 -16698.66200  90286.58965 -13959.38258  93636.07004 -28279.80744 
         139          140          141          142          143          144 
  3161.37722 -21664.90220 -21178.92996  61647.31023  33245.07004  -4363.99695 
         145          146          147          148          149          150 
   749.41644  26255.31023 -17916.96919  -9844.00841  21703.48343  20251.92460 
         151          152          153          154          155          156 
 -7774.72899 -14486.38258  45521.82984 100901.89683  87045.79062  -7978.82375 
         157          158          159          160          161          162 
-10190.24860 -58808.48880  23258.61742 -43497.03618   8733.79062 -13256.68977 
         163          164          165          166          167          168 
  6777.79062  66284.84616   3389.79062  24491.13703 -13456.44958  44353.17625 
         169          170          171          172          173          174 
 16296.24324   -148.27637 -22287.44958 -14820.34336  34190.96382  -8833.44958 
         175          176          177          178          179          180 
  3535.65664  71344.81839  -6393.72899  -7049.59501  18056.72363 -35841.22084 
         181          182          183          184          185          186 
 65096.48343  54353.31023 -47765.55579  40083.57819 -14850.20938 -17732.27637 
         187          188          189          190          191          192 
 51220.49975 -81972.98064  -4345.82375  15828.55042  76659.23179  -2315.03618 
         193          194          195          196          197          198 
 14246.79062  -6868.10317  23908.58965  28785.96382  -9497.51657   9175.07004 
         199          200          201          202          203          204 
  3158.79062  49737.44421  -1309.59501 -45271.92996  19884.65664 -15966.41035 
         205          206          207          208          209          210 
-48604.38258  99023.61742 -15930.31559  -6568.34336   8426.58965  15840.64518 
         211          212          213          214          215          216 
 -1897.44958 -21216.48880  14137.57819  24684.19256  -4902.00841 -38225.96919 
         217          218          219          220          221          222 
  -989.27637  27255.41644 -26554.17016 -20825.63423 -41175.34336  -9695.58356 
         223          224          225          226          227          228 
-23690.68977  -2508.86297  14229.31023  -4463.92996 125177.07004  67898.81839 
         229          230          231          232          233          234 
-13809.99695   2231.00305  29177.65664 -15918.00841   2026.37722 -38551.75676 
         235          236          237          238          239          240 
-49373.72899  17023.31023  60419.41644 -17956.87443 -12539.62278  -9054.96919 
         241          242          243          244          245          246 
-14290.10317 -21673.00841  15588.82984 -11078.92996   5157.37722 -16851.75676 
         247          248          249          250          251          252 
-30411.59501  -6968.62278   7241.65664 -16748.99695  -9278.96919 -18732.07540 
         253          254          255          256          257          258 
  8114.82984  21322.37722   -131.17016  20664.07004 -36260.62278  -6474.10317 
         259          260          261          262          263          264 
 28880.41644 -37172.52802 -13640.92996 -15742.35482  48561.79062 -35369.52802 
         265          266          267          268          269          270 
-49279.86297 -15947.79598  28181.79062 -11146.38258  84126.51120 -19337.75676 
         271          272          273          274          275          276 
 -5542.86297  14906.20402 123485.79062   8517.48343  56526.96382  -5206.86297 
         277          278          279          280          281          282 
   933.65664 -51186.83521  20261.13703  31581.89683  44523.41644 -21564.42181 
         283          284          285          286          287          288 
-34492.83521 -26111.04763  30145.20402  47997.37722  16726.65664  94499.72363 
         289          290          291          292          293          294 
 -9788.83521 -23162.24860 -15845.34336 102425.48343  63900.09780  25507.05858 
         295          296          297          298          299          300 
 70865.92460  82471.65664  24594.17625 -52770.48880 -10362.31559  44754.13703 
         301          302          303          304          305          306 
-84369.76821  18416.27101 -31744.79598 -26400.83521  89403.09780  26968.55042 
         307          308          309          310          311          312 
 -5339.17016 -37865.44958   -650.17016 -43285.99695 -32918.55579  37477.24324 
         313          314          315          316          317          318 
 31845.65664 -40289.75676 -27826.10317  -4426.27637 -56160.38258  -8192.24860 
         319          320          321          322          323          324 
-24367.86297 -17481.92996  52995.48343  -9429.86297  26218.96382  36168.48343 
         325          326          327          328          329          330 
-15374.20938 -30645.96919  19324.16479  30515.96382  30152.72363 -10605.51657 
         331          332          333          334          335          336 
 49081.91315   8010.31023 102091.82984  73238.82984  11147.41644  30734.09780 
         337          338          339          340          341          342 
-22045.58356  -9285.17016  10164.48343 -34123.27637  42607.82984 -17594.34336 
         343          344          345          346          347          348 
 40979.24324  50206.55042  -6736.79598 -43406.31559 -10841.58356  -9138.58356 
         349          350          351          352          353          354 
-31485.03618  29308.13703  -9349.58356  -4868.10317  28041.61742  29652.48343 
         355          356          357          358          359          360 
 -1456.07540 -37347.58356 -13987.83521  43606.65664 -19345.51657   1882.41644 
         361          362          363          364          365          366 
-19188.87443  47983.20402  14327.79062  -7672.41035 -65187.75676 -17534.20938 
         367          368          369          370          371          372 
  7412.07004  14135.00305  -1114.72899  11326.44421  -2778.20938  26864.55042 
         373          374          375          376          377          378 
  -613.58356 121353.95237 161726.71217  48223.20402  -6382.03618 -24215.20938 
         379          380          381          382          383          384 
137608.47198 -43225.59501 -12030.96919 137706.61742  -9517.75676   1529.65664 
         385          386          387          388          389          390 
 -4727.34336   -349.75676  -9786.41035  76213.44421  28781.07004  -8543.92996 
         391          392          393          394          395          396 
 20057.31023   8960.76285  27924.03081  -4907.27637  22309.72363 104298.13703 
         397          398          399          400          401          402 
 23617.64518  -9832.07540 -11632.07540  -2359.31559 -16062.96919    320.48343 
         403          404          405          406          407          408 
 53472.07004 -51848.92996   2324.68441   3639.00305 -13415.31559 -16375.92996 
         409          410          411          412          413          414 
 61880.65664  27219.48343   7597.17625  67601.37722  17807.27101 -21245.55579 
         415          416          417          418          419          420 
-11675.62278  24056.37722 -36649.44958  60106.41644  60012.72363  -5310.44958 
         421          422          423          424          425          426 
 50800.17625  -2008.68977 -47548.66200  27055.96382  13680.24324  11052.58965 
         427          428          429          430          431          432 
 -3835.10317  16094.92460 -14774.82375 -79706.35482 -41010.50025 117580.89683 
         433          434          435          436          437          438 
 15633.79062  -8587.44958  -8422.75676  -2618.75676 -21909.58356  27302.20402 
         439          440          441          442          443          444 
-68740.22084 -58298.34336  14820.03081  -7832.68977   4069.89683 -56984.14239 
         445          446          447          448          449          450 
 64537.31023 -44850.14239  -6940.03618   1702.37722  30539.64518  26995.12557 
         451          452          453          454          455          456 
105640.31023 -18102.10317  -5231.03618  23604.37722  15455.72363  32643.89683 
         457          458          459          460          461          462 
  5150.79062    478.37722 -19161.92996  13005.13703   2105.20402 -15815.20938 
         463          464          465          466          467          468 
 43339.96382 -16718.38258 -12997.03618 -12633.04763 -37148.10317  38387.13703 
         469          470          471          472          473          474 
  4389.65664 -17108.62278  27247.00305 -16914.58356 -53579.51657   9547.79062 
         475          476          477          478          479          480 
 -7392.44958   7749.65664  23043.82984  38530.24324 -30810.96919 -20626.90220 
         481          482          483          484          485          486 
 -7914.58356  -8709.34336  43520.47198  26331.31023   3349.09780  14861.33800 
         487          488          489          490          491          492 
 -7755.59501   2767.53897 -34914.62278   4534.65664 -10672.34336  91750.27101 
         493          494          495          496          497          498 
  2920.07004 -20424.38258 -42894.96919   4445.17625 109057.89683 -18360.55579 
         499          500          501          502          503          504 
-36544.86297  17405.48343   7526.07004  18536.27101   9007.16479   1216.61742 
         505          506          507          508          509          510 
 -9938.17016 -46981.92996  35318.79062  86542.96382 -13230.51657  90818.51120 
         511          512          513          514          515          516 
-21952.34336  43888.13703  14556.65664  -9699.82375 -16266.76821 -19706.79598 
         517          518          519          520          521          522 
-50510.55579  47204.41644  -9457.31559 -25617.20938  18051.09780   9098.82984 
         523          524          525          526          527          528 
 30737.81839  25769.41644 -32460.34336  54995.31023   4512.72363 -49767.72899 
         529          530          531          532          533          534 
 -5625.27637 -57531.14239   -276.86297  24993.48343 -16394.14239    -89.34336 
         535          536          537          538          539          540 
   879.24324  11918.55042   5861.91315  18122.20402  70328.27101 -10761.48880 
         541          542          543          544          545          546 
 -1519.58356 -20266.28783  30171.72363 -16223.03618 -58035.87443 -21709.31559 
         547          548          549          550          551          552 
 -6141.79598 -16198.86297 -45515.17016  53009.37722 -11653.58356 -21325.48880 
         553          554          555          556          557          558 
 38535.96382  12104.07004  15661.60596  -6220.99695  21604.48343  24953.89683 
         559          560          561          562          563          564 
  4551.07004 -33279.27637  -7910.83521 -43777.17016   1481.89683  95287.20402 
         565          566          567          568          569          570 
 51588.20402  16193.41644 -16102.20938  33530.96382  13311.85761  41182.72363 
         571          572          573          574          575          576 
-20168.58356  24201.61742  60011.65664 -43167.99695 -40160.92996   5239.82984 
         577          578          579          580          581          582 
 14673.07004  -5814.44958   9587.07004 -47489.92996 -11340.68977 -27374.83521 
         583          584          585          586          587          588 
 -8820.34336 -29521.44958  20275.40499   -710.82375  -5466.20938 -45314.41035 
         589          590          591          592          593          594 
-50998.66200 -18212.28783 -58364.11462    761.27101    347.79062 -15192.82375 
         595          596          597          598          599          600 
  9460.44421 -22566.86297  -7371.58356 -12623.20938  -4148.27637   5987.13703 
         601          602          603          604          605          606 
  3326.51120  -5571.68977 -27988.03618  39385.48343   9024.41644  26150.00305 
         607          608          609          610          611          612 
 29337.49975  18560.57819 -11717.44958 -22645.48880   -291.99695 -15558.24860 
         613          614          615          616          617          618 
 49652.89683  13962.00305  -3548.99695 120102.75140  97359.07004   2642.20402 
         619          620          621          622          623          624 
 34937.58965 -57157.83521  14511.07004 -16409.86297   7680.61742  -3068.99695 
         625          626          627          628          629          630 
-16363.22084 -13028.62278   4426.85761   6126.89683  33465.79062 -34225.63423 
         631          632          633          634          635          636 
 12371.48343 -19906.90220  -5446.58356   -968.23715 -29826.75676 -22372.66200 
         637          638          639          640          641          642 
 17445.48343 122579.58965 -10291.03618  12713.65664 -75254.92996 -41400.38258 
         643          644          645          646          647          648 
 54304.44421 -10574.44958  20013.13703  47060.07004  15962.13703  18160.65664 
         649          650          651          652          653          654 
 -5865.38258 -57010.55579  65094.57819 -35195.79598 -13017.48880  95929.27101 
         655          656          657          658          659          660 
 -9505.62278  10142.00305 -46361.14239  65484.20402  26757.48343  36178.85761 
         661          662          663          664          665          666 
  5205.41644 -16605.58356 -15161.42181  17052.37722 -31530.42181  61066.07004 
         667          668          669          670          671          672 
 51343.96382  12192.07004  11986.68441  11217.33800  -6313.92996  37835.72363 
         673          674          675          676          677          678 
 95317.27101  21412.82984 -12118.14239  51343.65664  18032.55042  50656.82984 
         679          680          681          682          683          684 
-48126.63423  -8196.34336 -16675.94142 -10768.79598 -14155.44958  16306.33800 
         685          686          687          688          689          690 
 56339.72363  30941.96382   1383.07004  19497.31023   7901.37722  44761.72363 
         691          692          693          694          695          696 
-16505.75676  -4077.75676  20133.89683 -19541.90220  -7931.51657   2190.57819 
         697          698          699          700          701          702 
-10579.10317 -76973.38258 -11339.17016  32711.44421 -15294.10317  25341.92460 
         703          704          705          706          707          708 
 16067.33800  12642.85761   9265.13703  53176.37722  56856.82984  15667.24324 
         709          710          711          712          713          714 
 -1257.75676 -33313.79598  31941.13703 -13432.62278  18333.92460 -48003.75676 
         715          716          717          718          719          720 
144111.07004  32217.95237  -4037.55579  13350.13703  17432.72363  53796.72363 
         721          722          723          724          725          726 
 29117.96382  32131.82984 -39736.17016 -20954.80744   4076.58965 -13893.14239 
         727          728          729          730          731          732 
-23048.66200  -3767.75676  38223.29878  41465.79062  39061.55042 -38614.41035 
         733          734          735          736          737          738 
-41425.90220  42724.48343   6895.20402 -35770.10317 128760.41644  -6479.62278 
         739          740          741          742          743          744 
 59779.51120  11443.65664   4722.13703 -39248.58356  -3550.14239  22838.00305 
         745          746          747          748          749          750 
135640.31023 -42606.51657   2890.41644 -43322.79598  21142.65664  -2329.44958 
         751          752          753          754          755          756 
-25162.83521 -41845.58356 -20641.58356  33566.24324  17203.64518 -11667.86297 
         757          758          759          760          761          762 
-73641.50025  -3064.96919 -17415.27637 -25393.62278  16061.29878  -1135.17016 
         763          764          765          766          767          768 
-37364.17016 121250.31023  10660.07004 -40425.55579 -27887.27637   4155.72363 
         769          770          771          772          773          774 
 13865.48343 -54815.04763   4850.65664  85589.24324  29102.79062  -2453.59501 
         775          776          777          778          779          780 
-42424.80744  -8673.75676   1289.20402  11851.24324  92368.61742  11321.60596 
         781          782          783          784          785          786 
 27428.24324  19350.71217 -38252.27637 -20689.58356  64382.71217   6106.37722 
         787          788          789          790          791          792 
 19103.44421  -6547.38258  32075.57819  28032.07004  -5767.96919  56718.85761 
         793          794          795          796          797          798 
-14763.92996  11840.99159  25297.13703  14684.00305  35120.99159 -38828.99695 
         799          800          801          802          803          804 
-27967.76821 -68156.62278 -22583.76821 -32730.24860  19485.82984 -22657.62278 
         805          806          807          808          809          810 
  -794.17016  60382.82984 -41511.34336 -32395.22084  89892.64518 -56076.34336 
         811          812          813          814          815          816 
 -8468.34336 -43148.51657  63819.82984  -8624.76821   2301.92460  49526.23179 
         817          818          819          820          821          822 
  2514.53897  -6607.17016 150784.68441 -13263.34336 -15915.92996  21397.82984 
         823          824          825          826          827          828 
 -7851.14239 -58727.66200  37324.37722 -12035.68977  13759.55042   7646.79062 
         829          830          831          832          833          834 
 44270.33800  40180.61742  14984.09780  -9541.58356  83265.89683  30704.27101 
         835          836          837          838          839          840 
-11495.75676 -25668.24860 -12090.41035 -45445.58356 -12316.04763  -7307.07540 
         841          842          843          844          845          846 
 19549.89683 -31125.51657  -2562.58356 -21708.42181  -2894.66200  15142.37722 
         847          848          849          850          851          852 
 22653.01936 -14804.51657 -26369.70122 -62037.52802  -6888.44958   4296.68441 
         853          854          855          856          857          858 
-17905.62278 -47254.86297  69274.51120   -693.44958 -17900.55579   2234.48343 
         859          860          861          862          863          864 
 14931.89683  18600.65664  66670.07004  -5972.51657  -1519.62278  22852.13703 
         865          866          867          868          869          870 
-37712.75676  28036.17625    480.07004  -2218.72899  38479.20402 -15266.17016 
         871          872          873          874          875          876 
 74225.44421  -4543.07540  -2471.34336 -13135.17016 -25704.10317  35708.44421 
         877          878          879          880          881          882 
 16286.79062   4653.48343  14103.07004  32385.79062  72057.61742  56066.75140 
         883          884          885          886          887          888 
 -2399.20938 -83688.22084  16504.68441 -22879.18161   4402.96382 131142.41644 
         889          890          891          892          893          894 
 61776.96382  41533.44421  18936.68441 -17877.07540 -42115.38258  32962.96382 
         895          896          897          898          899          900 
-18946.10317  85103.72363  32253.48343  30849.37722 -33328.44958   5672.27101 
         901          902          903          904          905          906 
 -9306.31559   1703.09780  66383.27101 -17207.55579   9931.79062  13248.17625 
         907          908          909          910          911          912 
-22494.17016  18140.07004 -23840.07540 -14641.44958  18134.96382   2630.24324 
         913          914          915          916          917          918 
 15878.24324  34268.48343   -442.27637 191866.13703   9743.13703 130749.01936 
         919          920          921          922          923          924 
  7802.55042  28845.03081  -5321.51657 146743.20402  -7791.99695  -2258.68977 
         925          926          927          928          929          930 
 30809.64518 -28744.07540 -10525.41035  65585.03081 -21231.11462 -51603.31559 
         931          932          933          934          935          936 
-41847.17016   4127.00305 -18727.68977  -2184.72899  -6834.58356  40444.31023 
         937          938          939          940          941          942 
-27612.51657  31390.31023  35168.27101  60247.92460  28733.51120 -45946.27637 
         943          944          945          946          947          948 
-21869.27637 -50228.72899 -10630.07540  92852.31023  28672.31023  24489.61742 
         949          950          951          952          953          954 
-46726.31559  17473.72363 -47049.55579  -8027.17016  52720.48343 113205.65664 
         955          956          957          958          959          960 
 -4902.10317  50567.47198 -13267.83521 -42568.79598 -26668.48880  21484.31023 
         961          962          963          964          965          966 
-10710.68977  -1093.66200   3969.89683  17984.37722 -41576.99695   3319.65664 
         967          968          969          970          971          972 
  1883.41644  33432.23179  41688.89683 -25762.55579   9035.00305   6466.68441 
         973          974          975          976          977          978 
-71622.10317  37713.79062   2863.55042  -4673.52802 -17690.63423  -1896.72899 
         979          980          981          982          983          984 
-41380.66200   8769.24324  53140.16479  45094.55042  66796.48343  49759.65664 
         985          986          987          988          989          990 
-41008.68977  -8077.75676  50030.55042  -6893.63423  62989.89683 -40322.24860 
         991          992          993          994          995          996 
-28422.79598 -33155.03618 -36659.58356  37528.31023 -13731.42181 -37028.27637 
         997          998          999         1000         1001         1002 
 36513.44421 -25238.38258 -10596.58356  36881.07004 -16107.04763   3293.19256 
        1003         1004         1005         1006         1007         1008 
 74929.68441 150654.09780 -83688.22084  52090.08635 -10966.28783  24484.53897 
        1009         1010         1011         1012         1013         1014 
-18712.11462  38330.68441 -29973.63423  47950.20402  60566.92460   -117.52802 
        1015         1016         1017         1018         1019         1020 
 -4046.00841  54427.13703 -21575.63423 -20792.98064  29704.64518  30131.08635 
        1021         1022         1023         1024         1025         1026 
 15536.96382  16800.09780 122449.88538 -10982.22084  40558.05858  90963.27101 
        1027         1028         1029         1030         1031         1032 
 -8001.22084  64032.67295 131610.51120 130608.01936  18660.71217  18918.31023 
        1033         1034         1035         1036         1037         1038 
-21162.04763 136769.47198  28546.92460   8818.84616  25415.77916 122102.95237 
        1039         1040         1041         1042         1043         1044 
  8418.23179 -10795.83521   1577.36577 159784.12557  10747.47198  71953.27101 
        1045         1046         1047         1048         1049         1050 
-25129.46103   1158.85761  19925.99159  12263.61742  23057.05858  18450.68441 
        1051         1052         1053         1054         1055         1056 
 26769.75140  -9364.87443  79421.75140 -30594.98064  14087.53897  30171.05858 
        1057         1058         1059         1060         1061         1062 
-13037.18161  48979.55042  41528.71217  28475.33800 105492.24324  32612.36577 
        1063         1064         1065         1066         1067         1068 
 52696.08635  -1755.80744   5007.32654  46894.71217 -18431.52802  16832.31023 
        1069         1070         1071         1072         1073         1074 
 31071.68441  21204.47198  11983.99159 -14642.87443   7310.36577  78882.85761 
        1075         1076         1077         1078         1079         1080 
151757.68441 -83567.39404  51751.25955 -10406.70122  28734.71217 -19366.28783 
        1081         1082         1083         1084         1085         1086 
 37996.51120 -28693.04763  46053.61742  60429.92460   3681.64518  -1185.42181 
        1087         1088         1089         1090         1091         1092 
 54592.31023 -22491.04763 -19823.39404  29652.23179  32539.25955  16610.13703 
        1093         1094         1095         1096         1097         1098 
129823.51120 132471.77916  14963.53897  17953.48343 -23337.22084 137332.47198 
        1099         1100         1101         1102         1103         1104 
 22958.75140   3833.25955 -40872.38258 -17775.55579 -13107.83521  38915.13703 
        1105         1106         1107         1108         1109         1110 
 -3451.48880  28545.44421  10648.19256   -267.38258 -13728.82375 -16625.24860 
        1111         1112         1113         1114         1115         1116 
 36772.92460  20951.13703 -29717.76821 -13515.17016  69853.07004 -19282.52802 
        1117         1118         1119         1120         1121         1122 
 14740.61742  19364.44421   3936.17625  -7650.20938   4099.33800 -26948.63423 
        1123         1124         1125         1126         1127         1128 
 32044.27101  51346.09780 -23909.68977 -19429.79598   7792.27101  19191.53897 
        1129         1130         1131         1132         1133         1134 
 43095.16479  20939.40499  49062.79062   8432.16479   2463.27101  -8794.38258 
        1135         1136         1137         1138         1139         1140 
-10418.42181  10813.96382  -5606.31559  35038.44421 -16300.94142  17400.85761 
        1141         1142         1143         1144         1145         1146 
  9107.31023  16860.48343 -15755.63423 -42904.39404  30238.20402  41935.72363 
        1147         1148         1149         1150         1151         1152 
 26245.13703  -1545.59501 -11111.27637  24329.79062  29894.13703 -11442.00841 
        1153         1154         1155         1156         1157         1158 
-21011.66200  -8695.03618  17287.92460  48945.27101 -33358.96919  33017.57819 
        1159         1160         1161         1162         1163         1164 
 14604.27101   9546.79062  -2126.65055  61978.37722  29593.61742  11459.03081 
        1165         1166         1167         1168         1169         1170 
 13992.82984  55680.85761  27984.79062  32033.20402   4308.51120   7606.85761 
        1171         1172         1173         1174         1175         1176 
 56115.79062  -7306.38258  13600.61742  19674.81839  -6069.62278  36856.75140 
        1177         1178         1179         1180         1181         1182 
-18875.20938  11295.00305  19896.37722  28730.27101  -8240.96919  27563.72363 
        1183         1184         1185         1186         1187         1188 
 38137.55042  -8593.27637 -25567.72899  -3517.87443  36229.61742 -19234.44958 
        1189         1190         1191         1192         1193         1194 
 25367.75140   6334.72363   2494.40499  12126.07004  18237.44421  -6302.03618 
        1195         1196         1197         1198         1199         1200 
-12047.34336  39593.31023  37294.81839  -2971.48880  -2007.86297  62874.37722 
        1201         1202         1203         1204         1205         1206 
 67235.65664  -3480.68977 -10341.79598 -19318.86297  31745.44421  -3009.90220 
        1207         1208         1209         1210         1211         1212 
  4434.68441 -25419.00841 -17813.79598  33688.55042  61456.13703  -9766.62278 
        1213         1214         1215         1216         1217         1218 
 -1397.68977  34637.37722  19218.44421  19469.20402 -17107.79598   2434.20402 
        1219         1220         1221         1222         1223         1224 
 20279.81839  32913.96382  17881.99159 -14993.34336  56959.96382 -11423.00841 
        1225         1226         1227         1228         1229         1230 
 -1471.44958   1171.13703  -9014.96919  29191.81839 -21366.03618  18178.20402 
        1231         1232         1233         1234         1235         1236 
  2308.48343  -5934.75676  30725.79062   2077.79062  -1068.62278  54241.58965 
        1237         1238         1239         1240         1241         1242 
 -5788.10317  46241.71217   4019.51120 -34647.94142   6628.31023  13170.40499 
        1243         1244         1245         1246         1247         1248 
  8840.65664  -7291.31559  -5268.03618  25621.00305 -35270.72899   1283.61742 
        1249         1250         1251         1252         1253         1254 
  2685.89683 -22614.90220  -9535.10317  11577.09780  31068.61742   2389.65664 
        1255         1256         1257         1258         1259         1260 
 18308.81839  14925.68441   4157.55042 -11167.59501 -15329.34336  52233.61742 
        1261         1262         1263         1264         1265         1266 
 32256.33800  10409.65664  44284.79062  -1251.20938  10029.47198  -9251.27637 
        1267         1268         1269         1270         1271         1272 
  5105.51120  26428.44421  17031.58965  -4984.07540   5439.37722  23972.72363 
        1273         1274         1275         1276         1277         1278 
-12679.00841  -2970.41035  21361.75140   7998.75140  -7822.98064 -14539.48880 
        1279         1280         1281         1282         1283         1284 
 30289.37722  -5275.99695  -7623.90220  20439.40499  -4264.24860  21814.55042 
        1285         1286         1287         1288         1289         1290 
  2947.37722   2481.36577   3892.88538  10336.82984  -9654.55579 -16882.83521 
        1291         1292         1293         1294         1295         1296 
 23388.72363 -33611.07540 -25555.07540 -13861.83521  22302.89683  -7610.79598 
        1297         1298         1299         1300         1301         1302 
 33606.55042  10566.25955  -1659.62278 -15493.55579 -20432.92996 -35454.87443 
        1303         1304         1305         1306         1307         1308 
-13209.10317  -8243.44958  -3779.94142  12324.07004  32376.00305  -3107.23715 
        1309         1310         1311         1312         1313         1314 
-21110.51657   2372.82984 -44045.92996  12889.31023 -25424.34336  13915.65664 
        1315         1316         1317         1318         1319         1320 
-12332.58356 -16132.51657 -10547.39404  -3601.92996 -18051.86297   -302.17016 
        1321         1322         1323         1324         1325         1326 
  3614.48343 -15597.24860  22487.13703 -14796.75676 -82312.52802  15067.48343 
        1327         1328         1329         1330         1331         1332 
 15081.82984 -46964.75676 -26230.27637 -14036.44958  11041.57819  -6193.11462 
        1333         1334         1335         1336         1337         1338 
 -3154.92996 -18111.24860 -19574.99695  -1484.55579   4803.13703 -15638.75676 
        1339         1340         1341         1342         1343         1344 
-43121.92996 -23085.92996  22455.41644  -7300.86297   3913.24324   4603.92460 
        1345         1346         1347         1348         1349         1350 
  3337.58965  -9776.10317 -22346.27637  -3420.34336   6071.41644 -20415.38258 
        1351         1352         1353         1354         1355         1356 
-34566.62278 -10324.92996  25896.00305 -15582.59501  -2707.23715   6196.41644 
        1357         1358         1359         1360         1361         1362 
-17191.72899  -4640.92996 -34712.96919  -8328.42181  12559.79062   6961.24324 
        1363         1364         1365         1366         1367         1368 
-45526.92996   4232.31023 -41913.99695  11562.07004  27803.72363 -13746.10317 
        1369         1370         1371         1372         1373         1374 
-82080.03618 -45797.44958   4997.65664  26635.79062 -55683.34336 -44363.96919 
        1375         1376         1377         1378         1379         1380 
-52028.90220 -33614.07540 -12505.27637  11397.65664 -14189.99695 -29513.24860 
        1381         1382         1383         1384         1385         1386 
 -9877.92996 -56202.68977   5621.07004 -13584.20938  12977.72363  20026.58965 
        1387         1388         1389         1390         1391         1392 
 -3057.34336  -3473.17016 -15098.10317  10446.13703 -45908.48880 -41409.11462 
        1393         1394         1395         1396         1397         1398 
-19008.75676 -20090.39404 -32023.18161  16229.82984 -12063.82375 -26575.74045 
        1399         1400         1401         1402         1403         1404 
  3076.72363 -70480.92996   8248.79062   4246.24324   6537.85761  -7533.68977 
        1405         1406         1407         1408         1409         1410 
 14245.13703  12318.89683 -32163.92996   7358.13703 -33687.75676   1928.82984 
        1411         1412         1413         1414         1415         1416 
-64687.04763 -14510.72899   3725.00305  11357.92460  -8194.17016  25058.31023 
        1417         1418         1419         1420         1421         1422 
-21288.90220  -2516.75676 -14134.92996  30415.07004  -8420.03618  -3377.65055 
        1423         1424         1425         1426         1427         1428 
 -9288.75676 -40743.41035   6708.65664  20455.07004  27183.24324 -14214.68977 
        1429         1430         1431         1432         1433         1434 
-23281.80744  -4809.75676   8880.68441  17757.37722 -88798.15384 -51216.62278 
        1435         1436         1437         1438         1439         1440 
 -4253.34336 -35224.10317   5286.00305   5551.65664 -28332.20938 -12438.62278 
        1441         1442         1443         1444         1445         1446 
  4568.48343  -7031.17016 -26188.03618  -1884.75676 -89109.76821 -27380.07540 
        1447         1448         1449         1450         1451         1452 
-76753.72899  -4037.48880 -24123.24860  -3850.41035   7739.72363  17788.37722 
        1453         1454         1455         1456         1457         1458 
-10834.20938 -16921.86297  -3312.34336  24478.96382 -17618.22084 -43171.42181 
        1459         1460         1461         1462         1463         1464 
-26800.96919 -14580.59501 -39919.20938   6136.89683  24175.79062 -35432.20938 
        1465         1466         1467         1468         1469         1470 
 34286.07004  14840.79062  -3509.34336 -30980.52802 -10526.92996 -36980.11462 
        1471         1472         1473         1474         1475         1476 
-46614.92996 -15246.83521 -27128.31559 -38681.48880 -12475.92996 -21227.03618 
        1477         1478         1479         1480         1481         1482 
-22143.41035 -15689.76821 -20083.31559 -23302.75676 -33942.52802  -9468.34336 
        1483         1484         1485         1486         1487         1488 
 -3954.68977  -3429.11462  12917.24324  32310.41644   -318.99695 -13785.41035 
        1489         1490         1491         1492         1493         1494 
 12111.17625 -45593.99695  15181.07004 -26934.17016  16968.41644  -7436.34336 
        1495         1496         1497         1498         1499         1500 
-10246.51657  -9787.63423  -4545.34336  -9402.27637  -1137.51657   8886.24324 
        1501         1502         1503         1504         1505         1506 
-17057.83521  18527.55042 -13894.92996 -84428.70122  11302.48343  12561.82984 
        1507         1508         1509         1510         1511         1512 
-43334.34336 -34303.44958 -14623.79598  21748.92460  -9674.46103  -9577.34336 
        1513         1514         1515         1516         1517         1518 
-13295.83521 -19540.75676   3196.20402   8592.72363 -15345.75676 -34271.41035 
        1519         1520         1521         1522         1523         1524 
-28729.92996  13442.89683 -11083.68977   6068.65664  11629.44421  -1291.58356 
        1525         1526         1527         1528         1529         1530 
-19606.27637 -24633.10317  -1772.99695  -1115.34336 -18340.96919 -35096.62278 
        1531         1532         1533         1534         1535         1536 
-14231.34336  21421.48343 -10454.94142  -9836.99695   -916.34336 -13072.14239 
        1537         1538         1539         1540         1541         1542 
 -3922.10317 -45142.72899 -11784.42181  15809.55042   4297.48343 -42252.92996 
        1543         1544         1545         1546         1547         1548 
 12936.07004 -48312.51657  14727.82984  29258.48343 -17297.86297 -71034.86297 
        1549         1550         1551         1552         1553         1554 
-43242.68977  -1310.10317  22977.20402 -58092.17016 -45519.20938 -38765.55579 
        1555         1556         1557         1558         1559         1560 
-39940.00841 -10924.44958   2453.72363 -15571.10317 -25150.24860 -13966.75676 
        1561         1562         1563         1564         1565         1566 
-54714.51657   2518.41644  -5450.86297   8414.96382   8842.41644    627.24324 
        1567         1568         1569         1570         1571         1572 
 -4175.75676  -6619.92996   6854.89683 -50931.07540 -51186.87443 -12957.75676 
        1573         1574         1575         1576         1577         1578 
-27337.39404 -33719.83521  21567.58965 -10994.23715 -27047.39404  -5477.27637 
        1579         1580         1581         1582         1583         1584 
-72839.92996   6864.20402   3939.07004   9267.79062  -4583.17016  22789.72363 
        1585         1586         1587         1588         1589         1590 
  9261.89683 -29843.51657   6510.96382 -27039.34336   3587.58965 -68226.04763 
        1591         1592         1593         1594         1595         1596 
 -6454.38258  10138.17625  13427.09780 -11443.27637  20792.55042 -28493.83521 
        1597         1598         1599         1600         1601         1602 
 -1656.34336 -16410.51657  26263.31023 -16820.20938 -57045.92996   1304.41644 
        1603         1604         1605         1606         1607         1608 
 -1760.27637 -16202.92996  17169.24324 -41704.58356 -44322.92996 -55409.38258 
        1609         1610         1611         1612         1613         1614 
-16399.90220 -81591.72899  -5220.75676 -50442.55579   8708.82984 -27763.96919 
        1615         1616         1617         1618         1619         1620 
-41317.17016 -17493.42181  10778.48343 -39446.20938 -15536.20938 -38836.55579 
        1621         1622         1623         1624         1625         1626 
-39133.27637 -43950.92996 -26792.62278 -13486.00841 -45119.34336 -30500.44958 
        1627         1628         1629         1630         1631         1632 
-18782.92996 -39016.38258  -7713.68977   1017.48343 -35580.58356   7613.41644 
        1633         1634         1635         1636         1637         1638 
 15558.65664 -11999.41035 -45758.20938 -42057.17016  -6206.14239  -6754.72899 
        1639         1640         1641         1642         1643         1644 
-37821.92996 -48004.55579 -27558.03618 -21080.55579 -18086.44958 -37662.83521 
        1645         1646         1647         1648         1649         1650 
-30316.51657  -2071.34336 -26877.55579 -38010.66200   1569.85761 -18977.10317 
        1651         1652         1653         1654         1655         1656 
-31347.79598   5201.72363  -9788.62278   4542.37722 -38141.10317   5043.20402 
        1657         1658         1659         1660         1661         1662 
-38502.79598 -22579.34336 -33252.51657 -18204.58356 -19142.38258 -14096.68977 
        1663         1664         1665         1666         1667         1668 
-23636.48880 -23409.17016  -7224.62278 -10701.14239  -7812.68977   6917.31023 
        1669         1670         1671         1672         1673         1674 
-17420.34336 -21334.75676 -36087.58356 -25792.92996 -39074.34336  -5155.75676 
        1675         1676         1677         1678         1679         1680 
-16139.92996 -47584.72899 -33455.62278 -20199.75676 -26995.34336   4829.61742 
        1681         1682         1683         1684         1685         1686 
-39325.51657  -5505.44958 -30811.55579  -5653.58356   4052.24324  -3549.51657 
        1687         1688         1689         1690         1691         1692 
-57178.14239 -24357.42181   3043.41644  -5495.34336 -44309.99695  -2560.79598 
        1693         1694         1695         1696         1697         1698 
-42256.38258 -37383.99695 -25757.68977 -47565.38258 -16866.20938 -54990.14239 
        1699         1700         1701         1702         1703         1704 
  8611.89683  -8880.27637 -15717.27637 -36812.41035   3729.13703   2162.37722 
        1705         1706         1707         1708         1709         1710 
-24132.10317  -9645.03618 -30878.38258 -73927.44958 -43805.51657    326.48343 
        1711         1712         1713         1714         1715         1716 
-45186.41035 -14690.10317 -39330.34336 -30257.55579 -62006.75676  -1645.82375 
        1717         1718         1719         1720         1721         1722 
-44038.58356  -8555.92996 -20318.20938  -1550.75676   4007.24324   6531.96382 
        1723         1724         1725         1726         1727         1728 
-38345.17016   3703.79062 -46409.55579 -39598.96919 -50307.72899  -6760.62278 
        1729         1730         1731         1732         1733         1734 
-11986.92996 -46132.92996  -3412.58356   8350.13703  21387.48343  -2029.99695 
        1735         1736         1737         1738         1739         1740 
  2295.72363  14353.00305 -35873.58356   5522.37722   -197.34336 -33872.51657 
        1741         1742         1743         1744         1745         1746 
-15474.76821 -32990.83521 -33961.38258 -22951.66200 -13062.83521   1989.31023 
        1747         1748         1749         1750         1751         1752 
-34717.86297  -9855.17016 -40820.75676 -35318.44958   4248.96382 -41227.17016 
        1753         1754         1755         1756         1757         1758 
  6870.79062 -47630.14239  -9038.44958  -9087.34336  -1495.20938  -3771.62278 
        1759         1760         1761         1762         1763         1764 
 -1448.10317 -40148.34336 -46142.27637 -38669.34336 -59325.66200  -7841.82375 
        1765         1766         1767         1768         1769         1770 
-21694.48880  -5028.20938 -33530.27637 -43112.14239 -43156.27637  -4461.92996 
        1771         1772         1773         1774         1775         1776 
  7082.13703 -49455.31559 -48277.86297   2529.89683 -32216.79598 -33628.62278 
        1777         1778         1779         1780         1781         1782 
-35693.58356 -19365.55579 -12123.34336 -50370.51657 -21578.55579 -10026.34336 
        1783         1784         1785         1786         1787         1788 
  6756.41644  -2888.34336  14803.65664 -43172.83521 -13760.34336 -33726.62278 
        1789         1790         1791         1792         1793         1794 
-26802.17016 -53377.07540 -49953.34336 -45081.66200 -51205.92996 -13775.14239 
        1795         1796         1797         1798         1799         1800 
-11052.10317 -73214.51657 -35925.44958 -43413.42181  -8592.86297 -26182.27637 
        1801         1802         1803         1804         1805         1806 
-43137.59501 -14982.18161 -31039.03618 -13010.99695 -34045.44958  11685.13703 
        1807         1808         1809         1810         1811         1812 
-26269.48880 -40649.75676 -29587.14239 -13683.20938   -575.92996 -53292.55579 
        1813         1814         1815         1816         1817         1818 
-26190.79598 -14391.62278 -30139.03618   5515.48343 -53858.90220 -10694.92996 
        1819         1820         1821         1822         1823         1824 
-23253.42181   -194.65055 -36683.75676 -55054.55579  -2091.51657 -45831.58356 
        1825         1826         1827         1828         1829         1830 
-44847.62278  17132.48343 -11115.58356  -6063.03618 -61806.10317 -17166.62278 
        1831         1832         1833         1834         1835         1836 
-29130.86297 -59403.07540   3688.07004  15487.24324  -9466.92996 -19800.17016 
        1837         1838         1839         1840         1841         1842 
-48209.44958   1721.82984 -34988.51657 -66339.62278   4267.31023 -12296.31559 
        1843         1844         1845         1846         1847         1848 
 10314.58965 -41912.17016 -43214.03618  17475.65664 -15089.79598 -34428.86297 
        1849         1850         1851         1852         1853         1854 
-10991.44958 -17676.51657     20.31023 -52814.34336    738.24324  -4113.44958 
        1855         1856         1857         1858         1859         1860 
-20555.68977  19042.65664 -39852.58356 -46182.75676 -57866.55579 -18636.07540 
        1861         1862         1863         1864         1865         1866 
-80176.31559   1845.00305 -51992.96919   4847.07004 -32302.55579 -44258.17016 
        1867         1868         1869         1870         1871         1872 
-25157.59501   6989.31023 -40559.03618 -19344.38258 -35280.96919 -32450.10317 
        1873         1874         1875         1876         1877         1878 
-43664.75676 -26452.62278 -17914.18161 -47952.34336 -29130.44958 -23388.10317 
        1879         1880         1881         1882         1883         1884 
-41035.96919  -9863.10317   5471.65664 -39514.17016   9188.58965  15900.65664 
        1885         1886         1887         1888         1889         1890 
-12156.82375 -46681.62278 -38743.17016  -2892.55579  -7735.90220 -38142.10317 
        1891         1892         1893         1894         1895         1896 
-42404.96919 -27753.62278 -20320.72899 -18601.86297 -39478.24860 -26537.34336 
        1897         1898         1899         1900         1901         1902 
   -92.34336 -28824.72899 -39384.24860   3039.27101 -16991.92996 -27091.79598 
        1903         1904         1905         1906         1907         1908 
  -424.44958  -5639.44958   1730.20402 -35328.27637   -288.96919 -42812.55579 
        1909         1910         1911         1912         1913         1914 
-23336.51657 -29439.34336 -23536.17016 -21522.55579 -10905.10317 -17245.31559 
        1915         1916         1917         1918         1919         1920 
-18396.58356  -4073.03618 -14425.72899 -12977.44958   3900.13703 -13897.34336 
        1921         1922         1923         1924         1925         1926 
-19429.58356 -40646.34336 -23309.92996 -36786.17016  -6890.92996 -12428.34336 
        1927         1928         1929         1930         1931         1932 
-48721.72899 -39662.79598 -23673.34336 -29002.17016   1165.03081 -39643.34336 
        1933         1934         1935         1936         1937         1938 
 -6972.62278 -26589.38258  -8842.17016   -729.34336     88.24324 -54183.55579 
        1939         1940         1941         1942         1943         1944 
-26589.24860   6051.00305  -5897.75676 -44322.17016  -5464.96919 -43390.96919 
        1945         1946         1947         1948         1949         1950 
-35651.41035 -24624.92996 -48604.55579 -14753.79598 -58586.72899   3649.72363 
        1951         1952         1953         1954         1955         1956 
-13499.27637 -16729.68977 -41594.58356    411.55042   2385.20402 -27665.10317 
        1957         1958         1959         1960         1961         1962 
 -2409.27637 -30823.96919 -75216.44958 -37550.34336   -932.92996 -42368.82375 
        1963         1964         1965         1966         1967         1968 
-10468.92996 -38958.34336 -31296.55579 -63022.17016  -2347.99695 -45429.17016 
        1969         1970         1971         1972         1973         1974 
 -7299.92996 -20546.62278  -5889.92996   6694.24324   7002.96382 -39828.17016 
        1975         1976         1977         1978         1979         1980 
  2022.96382 -50383.72899 -38617.38258 -46094.72899  -6567.62278 -10442.92996 
        1981         1982         1983         1984         1985         1986 
-44834.75676  -5306.58356   7493.96382  18682.48343   -971.41035  -2036.86297 
        1987         1988         1989         1990         1991         1992 
 16240.58965 -42243.75676   4499.37722  -2304.75676 -36759.27637 -12454.76821 
        1993         1994         1995         1996         1997         1998 
-36595.00841 -35600.38258 -17609.48880  -9713.66200   6657.07004 -29117.27637 
        1999         2000 
 -9796.17016 -40455.75676 </code></pre>
</div>
</div>
<p>This calculates the residuals for each of the new predictions. These residuals are large, meaning the model is missing the actual value by a lot. This makes sense since the model is only accounting for 11.6% of the variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.435462e-11</code></pre>
</div>
</div>
<p>The mean of the residuals is 9.43562e-11, which is close to zero. The only issue with the model is the spread and pattern of the residuals. Let’s visually plot the model ti check heteroskedasticity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-22-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-22-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the residual vs fitted graph (first graph), the red line isn’t flat, it curves slightly. This means the residuals spread unevenly as fitted values change. This shows non-linearity and heterskedasticity.</p>
<p>In the Q-Q Residuals graph, both tails deviate from the straight line. This suggests the residuals are not normal, and that there are heavier upper tails.</p>
<p>In the scale-location plot, we can see the red line trends slightly upward, meaning variance increases with fitted variables. This fits with the other two graphs and confirms heteroskedasticity. The spread of the residuals isn’t constant.</p>
<p>In the last graph, residuals vs leverage, we can see that there are a few outliers affecting our regression line. These could be age outliers or income outliers.</p>
<p>Let’s look at the spread of the residuals in a histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals have a bell-shaped curve but are slightly positively skewed. This means the model is not appropriate for the data. This may mean needing to transform variables as logorithmic, add predictors such as education or experience, or use a non-linear model, which we will learn in Statistics II.</p>
<p>Typically, I wouldn’t calculate confidence intervals for an incorrect model, but just to show I know how to do it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confidence intervals for new values</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span>population<span class="sc">$</span>Age</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(population<span class="sc">$</span>Income <span class="sc">~</span> x)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, population, <span class="at">interval =</span><span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          fit       lwr      upr
1    155390.4 150933.57 159847.2
2    105549.0 103109.52 107988.5
3    135453.8 133097.22 137810.5
4    131023.5 129034.23 133012.7
5    139884.2 137104.62 142663.7
6    119947.6 118371.26 121524.0
7    139884.2 137104.62 142663.7
8    119947.6 118371.26 121524.0
9    148744.9 145030.32 152459.4
10   112194.5 110298.32 114090.7
11   108871.8 106724.35 111019.2
12   107764.2 105523.20 110005.1
13   105549.0 103109.52 107988.5
14   147637.3 144043.83 151230.7
15   112194.5 110298.32 114090.7
16   116624.9 114968.06 118281.7
17   139884.2 137104.62 142663.7
18   108871.8 106724.35 111019.2
19   129915.9 128005.94 131825.9
20   115517.3 113813.26 117221.3
21   134346.2 132087.81 136604.7
22   129915.9 128005.94 131825.9
23   134346.2 132087.81 136604.7
24   129915.9 128005.94 131825.9
25   109979.3 107921.00 112037.7
26   121055.2 119483.52 122626.9
27   124378.0 122752.56 126003.4
28   127700.7 125929.40 129472.1
29   118840.0 117247.67 120432.4
30   150960.0 147000.78 154919.3
31   121055.2 119483.52 122626.9
32   111086.9 109112.55 113061.3
33   114409.7 112649.49 116169.9
34   144314.5 141078.17 147550.9
35   117732.4 116113.09 119351.8
36   108871.8 106724.35 111019.2
37   115517.3 113813.26 117221.3
38   122162.8 120584.36 123741.2
39   122162.8 120584.36 123741.2
40   107764.2 105523.20 110005.1
41   114409.7 112649.49 116169.9
42   109979.3 107921.00 112037.7
43   129915.9 128005.94 131825.9
44   107764.2 105523.20 110005.1
45   145422.1 142067.86 148776.4
46   119947.6 118371.26 121524.0
47   124378.0 122752.56 126003.4
48   106656.6 104318.10 108995.1
49   124378.0 122752.56 126003.4
50   112194.5 110298.32 114090.7
51   113302.1 111477.56 115126.6
52   114409.7 112649.49 116169.9
53   108871.8 106724.35 111019.2
54   115517.3 113813.26 117221.3
55   144314.5 141078.17 147550.9
56   109979.3 107921.00 112037.7
57   138776.6 136106.60 141446.6
58   115517.3 113813.26 117221.3
59   106656.6 104318.10 108995.1
60   106656.6 104318.10 108995.1
61   111086.9 109112.55 113061.3
62   136561.4 134103.22 139019.6
63   148744.9 145030.32 152459.4
64   108871.8 106724.35 111019.2
65   109979.3 107921.00 112037.7
66   134346.2 132087.81 136604.7
67   113302.1 111477.56 115126.6
68   105549.0 103109.52 107988.5
69   122162.8 120584.36 123741.2
70   108871.8 106724.35 111019.2
71   114409.7 112649.49 116169.9
72   132131.1 130056.88 134205.3
73   137669.0 135106.23 140231.8
74   126593.1 124879.55 128306.7
75   125485.6 123820.87 127150.2
76   154282.8 149951.24 158614.4
77   118840.0 117247.67 120432.4
78   137669.0 135106.23 140231.8
79   124378.0 122752.56 126003.4
80   105549.0 103109.52 107988.5
81   129915.9 128005.94 131825.9
82   133238.7 131074.54 135402.8
83   107764.2 105523.20 110005.1
84   145422.1 142067.86 148776.4
85   138776.6 136106.60 141446.6
86   113302.1 111477.56 115126.6
87   111086.9 109112.55 113061.3
88   133238.7 131074.54 135402.8
89   114409.7 112649.49 116169.9
90   112194.5 110298.32 114090.7
91   143206.9 140087.16 146326.7
92   140991.8 138100.58 143883.0
93   117732.4 116113.09 119351.8
94   103333.8 100683.52 105984.1
95   140991.8 138100.58 143883.0
96   145422.1 142067.86 148776.4
97   148744.9 145030.32 152459.4
98   118840.0 117247.67 120432.4
99   121055.2 119483.52 122626.9
100  121055.2 119483.52 122626.9
101  126593.1 124879.55 128306.7
102  107764.2 105523.20 110005.1
103  107764.2 105523.20 110005.1
104  119947.6 118371.26 121524.0
105  109979.3 107921.00 112037.7
106  124378.0 122752.56 126003.4
107  124378.0 122752.56 126003.4
108  116624.9 114968.06 118281.7
109  114409.7 112649.49 116169.9
110  119947.6 118371.26 121524.0
111  115517.3 113813.26 117221.3
112  106656.6 104318.10 108995.1
113  112194.5 110298.32 114090.7
114  108871.8 106724.35 111019.2
115  119947.6 118371.26 121524.0
116  133238.7 131074.54 135402.8
117  114409.7 112649.49 116169.9
118  111086.9 109112.55 113061.3
119  106656.6 104318.10 108995.1
120  121055.2 119483.52 122626.9
121  108871.8 106724.35 111019.2
122  126593.1 124879.55 128306.7
123  107764.2 105523.20 110005.1
124  150960.0 147000.78 154919.3
125  111086.9 109112.55 113061.3
126  114409.7 112649.49 116169.9
127  125485.6 123820.87 127150.2
128  114409.7 112649.49 116169.9
129  118840.0 117247.67 120432.4
130  113302.1 111477.56 115126.6
131  107764.2 105523.20 110005.1
132  113302.1 111477.56 115126.6
133  111086.9 109112.55 113061.3
134  133238.7 131074.54 135402.8
135  104441.4 101897.87 106984.9
136  123270.4 121673.91 124866.9
137  111086.9 109112.55 113061.3
138  154282.8 149951.24 158614.4
139  119947.6 118371.26 121524.0
140  129915.9 128005.94 131825.9
141  111086.9 109112.55 113061.3
142  114409.7 112649.49 116169.9
143  111086.9 109112.55 113061.3
144  105549.0 103109.52 107988.5
145  106656.6 104318.10 108995.1
146  114409.7 112649.49 116169.9
147  124378.0 122752.56 126003.4
148  137669.0 135106.23 140231.8
149  112194.5 110298.32 114090.7
150  132131.1 130056.88 134205.3
151  127700.7 125929.40 129472.1
152  123270.4 121673.91 124866.9
153  107764.2 105523.20 110005.1
154  113302.1 111477.56 115126.6
155  121055.2 119483.52 122626.9
156  103333.8 100683.52 105984.1
157  134346.2 132087.81 136604.7
158  131023.5 129034.23 133012.7
159  123270.4 121673.91 124866.9
160  118840.0 117247.67 120432.4
161  121055.2 119483.52 122626.9
162  114409.7 112649.49 116169.9
163  121055.2 119483.52 122626.9
164  158713.2 153877.68 163548.6
165  121055.2 119483.52 122626.9
166  116624.9 114968.06 118281.7
167  117732.4 116113.09 119351.8
168  103333.8 100683.52 105984.1
169  108871.8 106724.35 111019.2
170  115517.3 113813.26 117221.3
171  117732.4 116113.09 119351.8
172  109979.3 107921.00 112037.7
173  118840.0 117247.67 120432.4
174  117732.4 116113.09 119351.8
175  109979.3 107921.00 112037.7
176  139884.2 137104.62 142663.7
177  127700.7 125929.40 129472.1
178  138776.6 136106.60 141446.6
179  115517.3 113813.26 117221.3
180  153175.2 148968.37 157382.1
181  112194.5 110298.32 114090.7
182  114409.7 112649.49 116169.9
183  125485.6 123820.87 127150.2
184  136561.4 134103.22 139019.6
185  121055.2 119483.52 122626.9
186  115517.3 113813.26 117221.3
187  163143.5 157797.75 168489.2
188  156498.0 151915.39 161080.6
189  103333.8 100683.52 105984.1
190  117732.4 116113.09 119351.8
191  140991.8 138100.58 143883.0
192  118840.0 117247.67 120432.4
193  121055.2 119483.52 122626.9
194  113302.1 111477.56 115126.6
195  104441.4 101897.87 106984.9
196  118840.0 117247.67 120432.4
197  112194.5 110298.32 114090.7
198  111086.9 109112.55 113061.3
199  121055.2 119483.52 122626.9
200  125485.6 123820.87 127150.2
201  138776.6 136106.60 141446.6
202  111086.9 109112.55 113061.3
203  109979.3 107921.00 112037.7
204  104441.4 101897.87 106984.9
205  123270.4 121673.91 124866.9
206  123270.4 121673.91 124866.9
207  128808.3 126971.25 130645.4
208  109979.3 107921.00 112037.7
209  104441.4 101897.87 106984.9
210  142099.4 139094.69 145104.0
211  117732.4 116113.09 119351.8
212  131023.5 129034.23 133012.7
213  136561.4 134103.22 139019.6
214  154282.8 149951.24 158614.4
215  137669.0 135106.23 140231.8
216  124378.0 122752.56 126003.4
217  115517.3 113813.26 117221.3
218  106656.6 104318.10 108995.1
219  107764.2 105523.20 110005.1
220  152067.6 147984.91 156150.4
221  109979.3 107921.00 112037.7
222  106656.6 104318.10 108995.1
223  114409.7 112649.49 116169.9
224  116624.9 114968.06 118281.7
225  114409.7 112649.49 116169.9
226  111086.9 109112.55 113061.3
227  111086.9 109112.55 113061.3
228  139884.2 137104.62 142663.7
229  105549.0 103109.52 107988.5
230  105549.0 103109.52 107988.5
231  109979.3 107921.00 112037.7
232  137669.0 135106.23 140231.8
233  119947.6 118371.26 121524.0
234  108871.8 106724.35 111019.2
235  127700.7 125929.40 129472.1
236  114409.7 112649.49 116169.9
237  106656.6 104318.10 108995.1
238  148744.9 145030.32 152459.4
239  119947.6 118371.26 121524.0
240  124378.0 122752.56 126003.4
241  113302.1 111477.56 115126.6
242  137669.0 135106.23 140231.8
243  107764.2 105523.20 110005.1
244  111086.9 109112.55 113061.3
245  119947.6 118371.26 121524.0
246  108871.8 106724.35 111019.2
247  138776.6 136106.60 141446.6
248  119947.6 118371.26 121524.0
249  109979.3 107921.00 112037.7
250  105549.0 103109.52 107988.5
251  124378.0 122752.56 126003.4
252  132131.1 130056.88 134205.3
253  107764.2 105523.20 110005.1
254  119947.6 118371.26 121524.0
255  107764.2 105523.20 110005.1
256  111086.9 109112.55 113061.3
257  119947.6 118371.26 121524.0
258  113302.1 111477.56 115126.6
259  106656.6 104318.10 108995.1
260  144314.5 141078.17 147550.9
261  111086.9 109112.55 113061.3
262  142099.4 139094.69 145104.0
263  121055.2 119483.52 122626.9
264  144314.5 141078.17 147550.9
265  116624.9 114968.06 118281.7
266  122162.8 120584.36 123741.2
267  121055.2 119483.52 122626.9
268  123270.4 121673.91 124866.9
269  131023.5 129034.23 133012.7
270  108871.8 106724.35 111019.2
271  116624.9 114968.06 118281.7
272  122162.8 120584.36 123741.2
273  121055.2 119483.52 122626.9
274  112194.5 110298.32 114090.7
275  118840.0 117247.67 120432.4
276  116624.9 114968.06 118281.7
277  109979.3 107921.00 112037.7
278  135453.8 133097.22 137810.5
279  116624.9 114968.06 118281.7
280  113302.1 111477.56 115126.6
281  106656.6 104318.10 108995.1
282  136561.4 134103.22 139019.6
283  135453.8 133097.22 137810.5
284  150960.0 147000.78 154919.3
285  122162.8 120584.36 123741.2
286  119947.6 118371.26 121524.0
287  109979.3 107921.00 112037.7
288  115517.3 113813.26 117221.3
289  135453.8 133097.22 137810.5
290  134346.2 132087.81 136604.7
291  109979.3 107921.00 112037.7
292  112194.5 110298.32 114090.7
293  129915.9 128005.94 131825.9
294  143206.9 140087.16 146326.7
295  132131.1 130056.88 134205.3
296  109979.3 107921.00 112037.7
297  103333.8 100683.52 105984.1
298  131023.5 129034.23 133012.7
299  128808.3 126971.25 130645.4
300  116624.9 114968.06 118281.7
301  140991.8 138100.58 143883.0
302  127700.7 125929.40 129472.1
303  122162.8 120584.36 123741.2
304  135453.8 133097.22 137810.5
305  129915.9 128005.94 131825.9
306  117732.4 116113.09 119351.8
307  107764.2 105523.20 110005.1
308  117732.4 116113.09 119351.8
309  107764.2 105523.20 110005.1
310  105549.0 103109.52 107988.5
311  125485.6 123820.87 127150.2
312  108871.8 106724.35 111019.2
313  109979.3 107921.00 112037.7
314  108871.8 106724.35 111019.2
315  113302.1 111477.56 115126.6
316  115517.3 113813.26 117221.3
317  123270.4 121673.91 124866.9
318  134346.2 132087.81 136604.7
319  116624.9 114968.06 118281.7
320  111086.9 109112.55 113061.3
321  112194.5 110298.32 114090.7
322  116624.9 114968.06 118281.7
323  118840.0 117247.67 120432.4
324  112194.5 110298.32 114090.7
325  121055.2 119483.52 122626.9
326  124378.0 122752.56 126003.4
327  135453.8 133097.22 137810.5
328  118840.0 117247.67 120432.4
329  115517.3 113813.26 117221.3
330  112194.5 110298.32 114090.7
331  164251.1 158776.98 169725.2
332  114409.7 112649.49 116169.9
333  107764.2 105523.20 110005.1
334  107764.2 105523.20 110005.1
335  106656.6 104318.10 108995.1
336  129915.9 128005.94 131825.9
337  106656.6 104318.10 108995.1
338  107764.2 105523.20 110005.1
339  112194.5 110298.32 114090.7
340  115517.3 113813.26 117221.3
341  107764.2 105523.20 110005.1
342  109979.3 107921.00 112037.7
343  108871.8 106724.35 111019.2
344  117732.4 116113.09 119351.8
345  122162.8 120584.36 123741.2
346  128808.3 126971.25 130645.4
347  106656.6 104318.10 108995.1
348  106656.6 104318.10 108995.1
349  118840.0 117247.67 120432.4
350  116624.9 114968.06 118281.7
351  106656.6 104318.10 108995.1
352  113302.1 111477.56 115126.6
353  123270.4 121673.91 124866.9
354  112194.5 110298.32 114090.7
355  132131.1 130056.88 134205.3
356  106656.6 104318.10 108995.1
357  135453.8 133097.22 137810.5
358  109979.3 107921.00 112037.7
359  112194.5 110298.32 114090.7
360  106656.6 104318.10 108995.1
361  148744.9 145030.32 152459.4
362  122162.8 120584.36 123741.2
363  121055.2 119483.52 122626.9
364  104441.4 101897.87 106984.9
365  108871.8 106724.35 111019.2
366  121055.2 119483.52 122626.9
367  111086.9 109112.55 113061.3
368  105549.0 103109.52 107988.5
369  127700.7 125929.40 129472.1
370  125485.6 123820.87 127150.2
371  121055.2 119483.52 122626.9
372  117732.4 116113.09 119351.8
373  106656.6 104318.10 108995.1
374  150960.0 147000.78 154919.3
375  147637.3 144043.83 151230.7
376  122162.8 120584.36 123741.2
377  118840.0 117247.67 120432.4
378  121055.2 119483.52 122626.9
379  144314.5 141078.17 147550.9
380  138776.6 136106.60 141446.6
381  124378.0 122752.56 126003.4
382  123270.4 121673.91 124866.9
383  108871.8 106724.35 111019.2
384  109979.3 107921.00 112037.7
385  109979.3 107921.00 112037.7
386  108871.8 106724.35 111019.2
387  104441.4 101897.87 106984.9
388  125485.6 123820.87 127150.2
389  111086.9 109112.55 113061.3
390  111086.9 109112.55 113061.3
391  114409.7 112649.49 116169.9
392  102226.2  99466.78 104985.7
393  124378.0 122752.56 126003.4
394  115517.3 113813.26 117221.3
395  115517.3 113813.26 117221.3
396  116624.9 114968.06 118281.7
397  142099.4 139094.69 145104.0
398  132131.1 130056.88 134205.3
399  132131.1 130056.88 134205.3
400  128808.3 126971.25 130645.4
401  124378.0 122752.56 126003.4
402  112194.5 110298.32 114090.7
403  111086.9 109112.55 113061.3
404  111086.9 109112.55 113061.3
405  128808.3 126971.25 130645.4
406  105549.0 103109.52 107988.5
407  128808.3 126971.25 130645.4
408  111086.9 109112.55 113061.3
409  109979.3 107921.00 112037.7
410  112194.5 110298.32 114090.7
411  103333.8 100683.52 105984.1
412  119947.6 118371.26 121524.0
413  127700.7 125929.40 129472.1
414  125485.6 123820.87 127150.2
415  119947.6 118371.26 121524.0
416  119947.6 118371.26 121524.0
417  117732.4 116113.09 119351.8
418  106656.6 104318.10 108995.1
419  115517.3 113813.26 117221.3
420  117732.4 116113.09 119351.8
421  103333.8 100683.52 105984.1
422  114409.7 112649.49 116169.9
423  133238.7 131074.54 135402.8
424  118840.0 117247.67 120432.4
425  108871.8 106724.35 111019.2
426  104441.4 101897.87 106984.9
427  113302.1 111477.56 115126.6
428  132131.1 130056.88 134205.3
429  103333.8 100683.52 105984.1
430  142099.4 139094.69 145104.0
431  163143.5 157797.75 168489.2
432  113302.1 111477.56 115126.6
433  121055.2 119483.52 122626.9
434  117732.4 116113.09 119351.8
435  108871.8 106724.35 111019.2
436  108871.8 106724.35 111019.2
437  106656.6 104318.10 108995.1
438  122162.8 120584.36 123741.2
439  153175.2 148968.37 157382.1
440  109979.3 107921.00 112037.7
441  124378.0 122752.56 126003.4
442  114409.7 112649.49 116169.9
443  113302.1 111477.56 115126.6
444  126593.1 124879.55 128306.7
445  114409.7 112649.49 116169.9
446  126593.1 124879.55 128306.7
447  118840.0 117247.67 120432.4
448  119947.6 118371.26 121524.0
449  142099.4 139094.69 145104.0
450  148744.9 145030.32 152459.4
451  114409.7 112649.49 116169.9
452  113302.1 111477.56 115126.6
453  118840.0 117247.67 120432.4
454  119947.6 118371.26 121524.0
455  115517.3 113813.26 117221.3
456  113302.1 111477.56 115126.6
457  121055.2 119483.52 122626.9
458  119947.6 118371.26 121524.0
459  111086.9 109112.55 113061.3
460  116624.9 114968.06 118281.7
461  122162.8 120584.36 123741.2
462  121055.2 119483.52 122626.9
463  118840.0 117247.67 120432.4
464  123270.4 121673.91 124866.9
465  118840.0 117247.67 120432.4
466  150960.0 147000.78 154919.3
467  113302.1 111477.56 115126.6
468  116624.9 114968.06 118281.7
469  109979.3 107921.00 112037.7
470  119947.6 118371.26 121524.0
471  105549.0 103109.52 107988.5
472  106656.6 104318.10 108995.1
473  112194.5 110298.32 114090.7
474  121055.2 119483.52 122626.9
475  117732.4 116113.09 119351.8
476  109979.3 107921.00 112037.7
477  107764.2 105523.20 110005.1
478  108871.8 106724.35 111019.2
479  124378.0 122752.56 126003.4
480  129915.9 128005.94 131825.9
481  106656.6 104318.10 108995.1
482  109979.3 107921.00 112037.7
483  144314.5 141078.17 147550.9
484  114409.7 112649.49 116169.9
485  129915.9 128005.94 131825.9
486  133238.7 131074.54 135402.8
487  138776.6 136106.60 141446.6
488  149852.5 146015.95 153689.0
489  119947.6 118371.26 121524.0
490  109979.3 107921.00 112037.7
491  109979.3 107921.00 112037.7
492  127700.7 125929.40 129472.1
493  111086.9 109112.55 113061.3
494  123270.4 121673.91 124866.9
495  124378.0 122752.56 126003.4
496  103333.8 100683.52 105984.1
497  113302.1 111477.56 115126.6
498  125485.6 123820.87 127150.2
499  116624.9 114968.06 118281.7
500  112194.5 110298.32 114090.7
501  111086.9 109112.55 113061.3
502  127700.7 125929.40 129472.1
503  135453.8 133097.22 137810.5
504  123270.4 121673.91 124866.9
505  107764.2 105523.20 110005.1
506  111086.9 109112.55 113061.3
507  121055.2 119483.52 122626.9
508  118840.0 117247.67 120432.4
509  112194.5 110298.32 114090.7
510  131023.5 129034.23 133012.7
511  109979.3 107921.00 112037.7
512  116624.9 114968.06 118281.7
513  109979.3 107921.00 112037.7
514  103333.8 100683.52 105984.1
515  140991.8 138100.58 143883.0
516  122162.8 120584.36 123741.2
517  125485.6 123820.87 127150.2
518  106656.6 104318.10 108995.1
519  128808.3 126971.25 130645.4
520  121055.2 119483.52 122626.9
521  129915.9 128005.94 131825.9
522  107764.2 105523.20 110005.1
523  139884.2 137104.62 142663.7
524  106656.6 104318.10 108995.1
525  109979.3 107921.00 112037.7
526  114409.7 112649.49 116169.9
527  115517.3 113813.26 117221.3
528  127700.7 125929.40 129472.1
529  115517.3 113813.26 117221.3
530  126593.1 124879.55 128306.7
531  116624.9 114968.06 118281.7
532  112194.5 110298.32 114090.7
533  126593.1 124879.55 128306.7
534  109979.3 107921.00 112037.7
535  108871.8 106724.35 111019.2
536  117732.4 116113.09 119351.8
537  164251.1 158776.98 169725.2
538  122162.8 120584.36 123741.2
539  127700.7 125929.40 129472.1
540  131023.5 129034.23 133012.7
541  106656.6 104318.10 108995.1
542  147637.3 144043.83 151230.7
543  115517.3 113813.26 117221.3
544  118840.0 117247.67 120432.4
545  148744.9 145030.32 152459.4
546  128808.3 126971.25 130645.4
547  122162.8 120584.36 123741.2
548  116624.9 114968.06 118281.7
549  107764.2 105523.20 110005.1
550  119947.6 118371.26 121524.0
551  106656.6 104318.10 108995.1
552  131023.5 129034.23 133012.7
553  118840.0 117247.67 120432.4
554  111086.9 109112.55 113061.3
555  155390.4 150933.57 159847.2
556  105549.0 103109.52 107988.5
557  112194.5 110298.32 114090.7
558  113302.1 111477.56 115126.6
559  111086.9 109112.55 113061.3
560  115517.3 113813.26 117221.3
561  135453.8 133097.22 137810.5
562  107764.2 105523.20 110005.1
563  113302.1 111477.56 115126.6
564  122162.8 120584.36 123741.2
565  122162.8 120584.36 123741.2
566  106656.6 104318.10 108995.1
567  121055.2 119483.52 122626.9
568  118840.0 117247.67 120432.4
569  126593.1 124879.55 128306.7
570  115517.3 113813.26 117221.3
571  106656.6 104318.10 108995.1
572  123270.4 121673.91 124866.9
573  109979.3 107921.00 112037.7
574  105549.0 103109.52 107988.5
575  111086.9 109112.55 113061.3
576  107764.2 105523.20 110005.1
577  111086.9 109112.55 113061.3
578  117732.4 116113.09 119351.8
579  111086.9 109112.55 113061.3
580  111086.9 109112.55 113061.3
581  114409.7 112649.49 116169.9
582  135453.8 133097.22 137810.5
583  109979.3 107921.00 112037.7
584  117732.4 116113.09 119351.8
585  138776.6 136106.60 141446.6
586  103333.8 100683.52 105984.1
587  121055.2 119483.52 122626.9
588  104441.4 101897.87 106984.9
589  133238.7 131074.54 135402.8
590  147637.3 144043.83 151230.7
591  145422.1 142067.86 148776.4
592  127700.7 125929.40 129472.1
593  121055.2 119483.52 122626.9
594  103333.8 100683.52 105984.1
595  125485.6 123820.87 127150.2
596  116624.9 114968.06 118281.7
597  106656.6 104318.10 108995.1
598  121055.2 119483.52 122626.9
599  115517.3 113813.26 117221.3
600  116624.9 114968.06 118281.7
601  131023.5 129034.23 133012.7
602  114409.7 112649.49 116169.9
603  118840.0 117247.67 120432.4
604  112194.5 110298.32 114090.7
605  106656.6 104318.10 108995.1
606  105549.0 103109.52 107988.5
607  163143.5 157797.75 168489.2
608  136561.4 134103.22 139019.6
609  117732.4 116113.09 119351.8
610  131023.5 129034.23 133012.7
611  105549.0 103109.52 107988.5
612  134346.2 132087.81 136604.7
613  113302.1 111477.56 115126.6
614  105549.0 103109.52 107988.5
615  105549.0 103109.52 107988.5
616  134346.2 132087.81 136604.7
617  111086.9 109112.55 113061.3
618  122162.8 120584.36 123741.2
619  104441.4 101897.87 106984.9
620  135453.8 133097.22 137810.5
621  111086.9 109112.55 113061.3
622  116624.9 114968.06 118281.7
623  123270.4 121673.91 124866.9
624  105549.0 103109.52 107988.5
625  153175.2 148968.37 157382.1
626  119947.6 118371.26 121524.0
627  126593.1 124879.55 128306.7
628  113302.1 111477.56 115126.6
629  121055.2 119483.52 122626.9
630  152067.6 147984.91 156150.4
631  112194.5 110298.32 114090.7
632  129915.9 128005.94 131825.9
633  106656.6 104318.10 108995.1
634  102226.2  99466.78 104985.7
635  108871.8 106724.35 111019.2
636  133238.7 131074.54 135402.8
637  112194.5 110298.32 114090.7
638  104441.4 101897.87 106984.9
639  118840.0 117247.67 120432.4
640  109979.3 107921.00 112037.7
641  111086.9 109112.55 113061.3
642  123270.4 121673.91 124866.9
643  125485.6 123820.87 127150.2
644  117732.4 116113.09 119351.8
645  116624.9 114968.06 118281.7
646  111086.9 109112.55 113061.3
647  116624.9 114968.06 118281.7
648  109979.3 107921.00 112037.7
649  123270.4 121673.91 124866.9
650  125485.6 123820.87 127150.2
651  136561.4 134103.22 139019.6
652  122162.8 120584.36 123741.2
653  131023.5 129034.23 133012.7
654  127700.7 125929.40 129472.1
655  119947.6 118371.26 121524.0
656  105549.0 103109.52 107988.5
657  126593.1 124879.55 128306.7
658  122162.8 120584.36 123741.2
659  112194.5 110298.32 114090.7
660  126593.1 124879.55 128306.7
661  106656.6 104318.10 108995.1
662  106656.6 104318.10 108995.1
663  136561.4 134103.22 139019.6
664  119947.6 118371.26 121524.0
665  136561.4 134103.22 139019.6
666  111086.9 109112.55 113061.3
667  118840.0 117247.67 120432.4
668  111086.9 109112.55 113061.3
669  128808.3 126971.25 130645.4
670  133238.7 131074.54 135402.8
671  111086.9 109112.55 113061.3
672  115517.3 113813.26 117221.3
673  127700.7 125929.40 129472.1
674  107764.2 105523.20 110005.1
675  126593.1 124879.55 128306.7
676  109979.3 107921.00 112037.7
677  117732.4 116113.09 119351.8
678  107764.2 105523.20 110005.1
679  152067.6 147984.91 156150.4
680  109979.3 107921.00 112037.7
681  143206.9 140087.16 146326.7
682  122162.8 120584.36 123741.2
683  117732.4 116113.09 119351.8
684  133238.7 131074.54 135402.8
685  115517.3 113813.26 117221.3
686  118840.0 117247.67 120432.4
687  111086.9 109112.55 113061.3
688  114409.7 112649.49 116169.9
689  119947.6 118371.26 121524.0
690  115517.3 113813.26 117221.3
691  108871.8 106724.35 111019.2
692  108871.8 106724.35 111019.2
693  113302.1 111477.56 115126.6
694  129915.9 128005.94 131825.9
695  112194.5 110298.32 114090.7
696  136561.4 134103.22 139019.6
697  113302.1 111477.56 115126.6
698  123270.4 121673.91 124866.9
699  107764.2 105523.20 110005.1
700  125485.6 123820.87 127150.2
701  113302.1 111477.56 115126.6
702  132131.1 130056.88 134205.3
703  133238.7 131074.54 135402.8
704  126593.1 124879.55 128306.7
705  116624.9 114968.06 118281.7
706  119947.6 118371.26 121524.0
707  107764.2 105523.20 110005.1
708  108871.8 106724.35 111019.2
709  108871.8 106724.35 111019.2
710  122162.8 120584.36 123741.2
711  116624.9 114968.06 118281.7
712  119947.6 118371.26 121524.0
713  132131.1 130056.88 134205.3
714  108871.8 106724.35 111019.2
715  111086.9 109112.55 113061.3
716  150960.0 147000.78 154919.3
717  125485.6 123820.87 127150.2
718  116624.9 114968.06 118281.7
719  115517.3 113813.26 117221.3
720  115517.3 113813.26 117221.3
721  118840.0 117247.67 120432.4
722  107764.2 105523.20 110005.1
723  107764.2 105523.20 110005.1
724  154282.8 149951.24 158614.4
725  104441.4 101897.87 106984.9
726  126593.1 124879.55 128306.7
727  133238.7 131074.54 135402.8
728  108871.8 106724.35 111019.2
729  146529.7 143056.37 150003.0
730  121055.2 119483.52 122626.9
731  117732.4 116113.09 119351.8
732  104441.4 101897.87 106984.9
733  129915.9 128005.94 131825.9
734  112194.5 110298.32 114090.7
735  122162.8 120584.36 123741.2
736  113302.1 111477.56 115126.6
737  106656.6 104318.10 108995.1
738  119947.6 118371.26 121524.0
739  131023.5 129034.23 133012.7
740  109979.3 107921.00 112037.7
741  116624.9 114968.06 118281.7
742  106656.6 104318.10 108995.1
743  126593.1 124879.55 128306.7
744  105549.0 103109.52 107988.5
745  114409.7 112649.49 116169.9
746  112194.5 110298.32 114090.7
747  106656.6 104318.10 108995.1
748  122162.8 120584.36 123741.2
749  109979.3 107921.00 112037.7
750  117732.4 116113.09 119351.8
751  135453.8 133097.22 137810.5
752  106656.6 104318.10 108995.1
753  106656.6 104318.10 108995.1
754  108871.8 106724.35 111019.2
755  142099.4 139094.69 145104.0
756  116624.9 114968.06 118281.7
757  163143.5 157797.75 168489.2
758  124378.0 122752.56 126003.4
759  115517.3 113813.26 117221.3
760  119947.6 118371.26 121524.0
761  146529.7 143056.37 150003.0
762  107764.2 105523.20 110005.1
763  107764.2 105523.20 110005.1
764  114409.7 112649.49 116169.9
765  111086.9 109112.55 113061.3
766  125485.6 123820.87 127150.2
767  115517.3 113813.26 117221.3
768  115517.3 113813.26 117221.3
769  112194.5 110298.32 114090.7
770  150960.0 147000.78 154919.3
771  109979.3 107921.00 112037.7
772  108871.8 106724.35 111019.2
773  121055.2 119483.52 122626.9
774  138776.6 136106.60 141446.6
775  154282.8 149951.24 158614.4
776  108871.8 106724.35 111019.2
777  122162.8 120584.36 123741.2
778  108871.8 106724.35 111019.2
779  123270.4 121673.91 124866.9
780  155390.4 150933.57 159847.2
781  108871.8 106724.35 111019.2
782  147637.3 144043.83 151230.7
783  115517.3 113813.26 117221.3
784  106656.6 104318.10 108995.1
785  147637.3 144043.83 151230.7
786  119947.6 118371.26 121524.0
787  125485.6 123820.87 127150.2
788  123270.4 121673.91 124866.9
789  136561.4 134103.22 139019.6
790  111086.9 109112.55 113061.3
791  124378.0 122752.56 126003.4
792  126593.1 124879.55 128306.7
793  111086.9 109112.55 113061.3
794  137669.0 135106.23 140231.8
795  116624.9 114968.06 118281.7
796  105549.0 103109.52 107988.5
797  137669.0 135106.23 140231.8
798  105549.0 103109.52 107988.5
799  140991.8 138100.58 143883.0
800  119947.6 118371.26 121524.0
801  140991.8 138100.58 143883.0
802  134346.2 132087.81 136604.7
803  107764.2 105523.20 110005.1
804  119947.6 118371.26 121524.0
805  107764.2 105523.20 110005.1
806  107764.2 105523.20 110005.1
807  109979.3 107921.00 112037.7
808  153175.2 148968.37 157382.1
809  142099.4 139094.69 145104.0
810  109979.3 107921.00 112037.7
811  109979.3 107921.00 112037.7
812  112194.5 110298.32 114090.7
813  107764.2 105523.20 110005.1
814  140991.8 138100.58 143883.0
815  132131.1 130056.88 134205.3
816  140991.8 138100.58 143883.0
817  149852.5 146015.95 153689.0
818  107764.2 105523.20 110005.1
819  128808.3 126971.25 130645.4
820  109979.3 107921.00 112037.7
821  111086.9 109112.55 113061.3
822  107764.2 105523.20 110005.1
823  126593.1 124879.55 128306.7
824  133238.7 131074.54 135402.8
825  119947.6 118371.26 121524.0
826  114409.7 112649.49 116169.9
827  117732.4 116113.09 119351.8
828  121055.2 119483.52 122626.9
829  133238.7 131074.54 135402.8
830  123270.4 121673.91 124866.9
831  129915.9 128005.94 131825.9
832  106656.6 104318.10 108995.1
833  113302.1 111477.56 115126.6
834  127700.7 125929.40 129472.1
835  108871.8 106724.35 111019.2
836  134346.2 132087.81 136604.7
837  104441.4 101897.87 106984.9
838  106656.6 104318.10 108995.1
839  150960.0 147000.78 154919.3
840  132131.1 130056.88 134205.3
841  113302.1 111477.56 115126.6
842  112194.5 110298.32 114090.7
843  106656.6 104318.10 108995.1
844  136561.4 134103.22 139019.6
845  133238.7 131074.54 135402.8
846  119947.6 118371.26 121524.0
847  156498.0 151915.39 161080.6
848  112194.5 110298.32 114090.7
849  146529.7 143056.37 150003.0
850  144314.5 141078.17 147550.9
851  117732.4 116113.09 119351.8
852  128808.3 126971.25 130645.4
853  119947.6 118371.26 121524.0
854  116624.9 114968.06 118281.7
855  131023.5 129034.23 133012.7
856  117732.4 116113.09 119351.8
857  125485.6 123820.87 127150.2
858  112194.5 110298.32 114090.7
859  113302.1 111477.56 115126.6
860  109979.3 107921.00 112037.7
861  111086.9 109112.55 113061.3
862  112194.5 110298.32 114090.7
863  119947.6 118371.26 121524.0
864  116624.9 114968.06 118281.7
865  108871.8 106724.35 111019.2
866  103333.8 100683.52 105984.1
867  111086.9 109112.55 113061.3
868  127700.7 125929.40 129472.1
869  122162.8 120584.36 123741.2
870  107764.2 105523.20 110005.1
871  125485.6 123820.87 127150.2
872  132131.1 130056.88 134205.3
873  109979.3 107921.00 112037.7
874  107764.2 105523.20 110005.1
875  113302.1 111477.56 115126.6
876  125485.6 123820.87 127150.2
877  121055.2 119483.52 122626.9
878  112194.5 110298.32 114090.7
879  111086.9 109112.55 113061.3
880  121055.2 119483.52 122626.9
881  123270.4 121673.91 124866.9
882  134346.2 132087.81 136604.7
883  121055.2 119483.52 122626.9
884  153175.2 148968.37 157382.1
885  128808.3 126971.25 130645.4
886  139884.2 137104.62 142663.7
887  118840.0 117247.67 120432.4
888  106656.6 104318.10 108995.1
889  118840.0 117247.67 120432.4
890  125485.6 123820.87 127150.2
891  128808.3 126971.25 130645.4
892  132131.1 130056.88 134205.3
893  123270.4 121673.91 124866.9
894  118840.0 117247.67 120432.4
895  113302.1 111477.56 115126.6
896  115517.3 113813.26 117221.3
897  112194.5 110298.32 114090.7
898  119947.6 118371.26 121524.0
899  117732.4 116113.09 119351.8
900  127700.7 125929.40 129472.1
901  128808.3 126971.25 130645.4
902  129915.9 128005.94 131825.9
903  127700.7 125929.40 129472.1
904  125485.6 123820.87 127150.2
905  121055.2 119483.52 122626.9
906  103333.8 100683.52 105984.1
907  107764.2 105523.20 110005.1
908  111086.9 109112.55 113061.3
909  132131.1 130056.88 134205.3
910  117732.4 116113.09 119351.8
911  118840.0 117247.67 120432.4
912  108871.8 106724.35 111019.2
913  108871.8 106724.35 111019.2
914  112194.5 110298.32 114090.7
915  115517.3 113813.26 117221.3
916  116624.9 114968.06 118281.7
917  116624.9 114968.06 118281.7
918  156498.0 151915.39 161080.6
919  117732.4 116113.09 119351.8
920  124378.0 122752.56 126003.4
921  112194.5 110298.32 114090.7
922  122162.8 120584.36 123741.2
923  105549.0 103109.52 107988.5
924  114409.7 112649.49 116169.9
925  142099.4 139094.69 145104.0
926  132131.1 130056.88 134205.3
927  104441.4 101897.87 106984.9
928  124378.0 122752.56 126003.4
929  145422.1 142067.86 148776.4
930  128808.3 126971.25 130645.4
931  107764.2 105523.20 110005.1
932  105549.0 103109.52 107988.5
933  114409.7 112649.49 116169.9
934  127700.7 125929.40 129472.1
935  106656.6 104318.10 108995.1
936  114409.7 112649.49 116169.9
937  112194.5 110298.32 114090.7
938  114409.7 112649.49 116169.9
939  127700.7 125929.40 129472.1
940  132131.1 130056.88 134205.3
941  131023.5 129034.23 133012.7
942  115517.3 113813.26 117221.3
943  115517.3 113813.26 117221.3
944  127700.7 125929.40 129472.1
945  132131.1 130056.88 134205.3
946  114409.7 112649.49 116169.9
947  114409.7 112649.49 116169.9
948  123270.4 121673.91 124866.9
949  128808.3 126971.25 130645.4
950  115517.3 113813.26 117221.3
951  125485.6 123820.87 127150.2
952  107764.2 105523.20 110005.1
953  112194.5 110298.32 114090.7
954  109979.3 107921.00 112037.7
955  113302.1 111477.56 115126.6
956  144314.5 141078.17 147550.9
957  135453.8 133097.22 137810.5
958  122162.8 120584.36 123741.2
959  131023.5 129034.23 133012.7
960  114409.7 112649.49 116169.9
961  114409.7 112649.49 116169.9
962  133238.7 131074.54 135402.8
963  113302.1 111477.56 115126.6
964  119947.6 118371.26 121524.0
965  105549.0 103109.52 107988.5
966  109979.3 107921.00 112037.7
967  106656.6 104318.10 108995.1
968  140991.8 138100.58 143883.0
969  113302.1 111477.56 115126.6
970  125485.6 123820.87 127150.2
971  105549.0 103109.52 107988.5
972  128808.3 126971.25 130645.4
973  113302.1 111477.56 115126.6
974  121055.2 119483.52 122626.9
975  117732.4 116113.09 119351.8
976  144314.5 141078.17 147550.9
977  152067.6 147984.91 156150.4
978  127700.7 125929.40 129472.1
979  133238.7 131074.54 135402.8
980  108871.8 106724.35 111019.2
981  135453.8 133097.22 137810.5
982  117732.4 116113.09 119351.8
983  112194.5 110298.32 114090.7
984  109979.3 107921.00 112037.7
985  114409.7 112649.49 116169.9
986  108871.8 106724.35 111019.2
987  117732.4 116113.09 119351.8
988  152067.6 147984.91 156150.4
989  113302.1 111477.56 115126.6
990  134346.2 132087.81 136604.7
991  122162.8 120584.36 123741.2
992  118840.0 117247.67 120432.4
993  106656.6 104318.10 108995.1
994  114409.7 112649.49 116169.9
995  136561.4 134103.22 139019.6
996  115517.3 113813.26 117221.3
997  125485.6 123820.87 127150.2
998  123270.4 121673.91 124866.9
999  106656.6 104318.10 108995.1
1000 111086.9 109112.55 113061.3
1001 150960.0 147000.78 154919.3
1002 154282.8 149951.24 158614.4
1003 128808.3 126971.25 130645.4
1004 129915.9 128005.94 131825.9
1005 153175.2 148968.37 157382.1
1006 162035.9 156818.23 167253.6
1007 147637.3 144043.83 151230.7
1008 149852.5 146015.95 153689.0
1009 145422.1 142067.86 148776.4
1010 128808.3 126971.25 130645.4
1011 152067.6 147984.91 156150.4
1012 122162.8 120584.36 123741.2
1013 132131.1 130056.88 134205.3
1014 144314.5 141078.17 147550.9
1015 137669.0 135106.23 140231.8
1016 116624.9 114968.06 118281.7
1017 152067.6 147984.91 156150.4
1018 156498.0 151915.39 161080.6
1019 142099.4 139094.69 145104.0
1020 162035.9 156818.23 167253.6
1021 118840.0 117247.67 120432.4
1022 129915.9 128005.94 131825.9
1023 145422.1 142067.86 148776.4
1024 153175.2 148968.37 157382.1
1025 143206.9 140087.16 146326.7
1026 127700.7 125929.40 129472.1
1027 153175.2 148968.37 157382.1
1028 160928.3 155838.39 166018.3
1029 131023.5 129034.23 133012.7
1030 156498.0 151915.39 161080.6
1031 147637.3 144043.83 151230.7
1032 114409.7 112649.49 116169.9
1033 150960.0 147000.78 154919.3
1034 144314.5 141078.17 147550.9
1035 132131.1 130056.88 134205.3
1036 158713.2 153877.68 163548.6
1037 153175.2 148968.37 157382.1
1038 150960.0 147000.78 154919.3
1039 140991.8 138100.58 143883.0
1040 135453.8 133097.22 137810.5
1041 152067.6 147984.91 156150.4
1042 148744.9 145030.32 152459.4
1043 144314.5 141078.17 147550.9
1044 127700.7 125929.40 129472.1
1045 149852.5 146015.95 153689.0
1046 126593.1 124879.55 128306.7
1047 137669.0 135106.23 140231.8
1048 123270.4 121673.91 124866.9
1049 143206.9 140087.16 146326.7
1050 128808.3 126971.25 130645.4
1051 134346.2 132087.81 136604.7
1052 148744.9 145030.32 152459.4
1053 134346.2 132087.81 136604.7
1054 156498.0 151915.39 161080.6
1055 149852.5 146015.95 153689.0
1056 143206.9 140087.16 146326.7
1057 139884.2 137104.62 142663.7
1058 117732.4 116113.09 119351.8
1059 147637.3 144043.83 151230.7
1060 133238.7 131074.54 135402.8
1061 108871.8 106724.35 111019.2
1062 152067.6 147984.91 156150.4
1063 162035.9 156818.23 167253.6
1064 154282.8 149951.24 158614.4
1065 165358.7 159755.95 170961.4
1066 147637.3 144043.83 151230.7
1067 144314.5 141078.17 147550.9
1068 114409.7 112649.49 116169.9
1069 128808.3 126971.25 130645.4
1070 144314.5 141078.17 147550.9
1071 137669.0 135106.23 140231.8
1072 148744.9 145030.32 152459.4
1073 152067.6 147984.91 156150.4
1074 126593.1 124879.55 128306.7
1075 128808.3 126971.25 130645.4
1076 155390.4 150933.57 159847.2
1077 159820.7 154858.21 164783.3
1078 146529.7 143056.37 150003.0
1079 147637.3 144043.83 151230.7
1080 147637.3 144043.83 151230.7
1081 131023.5 129034.23 133012.7
1082 150960.0 147000.78 154919.3
1083 123270.4 121673.91 124866.9
1084 132131.1 130056.88 134205.3
1085 142099.4 139094.69 145104.0
1086 136561.4 134103.22 139019.6
1087 114409.7 112649.49 116169.9
1088 150960.0 147000.78 154919.3
1089 155390.4 150933.57 159847.2
1090 140991.8 138100.58 143883.0
1091 159820.7 154858.21 164783.3
1092 116624.9 114968.06 118281.7
1093 131023.5 129034.23 133012.7
1094 153175.2 148968.37 157382.1
1095 149852.5 146015.95 153689.0
1096 112194.5 110298.32 114090.7
1097 153175.2 148968.37 157382.1
1098 144314.5 141078.17 147550.9
1099 134346.2 132087.81 136604.7
1100 159820.7 154858.21 164783.3
1101 123270.4 121673.91 124866.9
1102 125485.6 123820.87 127150.2
1103 135453.8 133097.22 137810.5
1104 116624.9 114968.06 118281.7
1105 131023.5 129034.23 133012.7
1106 125485.6 123820.87 127150.2
1107 154282.8 149951.24 158614.4
1108 123270.4 121673.91 124866.9
1109 103333.8 100683.52 105984.1
1110 134346.2 132087.81 136604.7
1111 132131.1 130056.88 134205.3
1112 116624.9 114968.06 118281.7
1113 140991.8 138100.58 143883.0
1114 107764.2 105523.20 110005.1
1115 111086.9 109112.55 113061.3
1116 144314.5 141078.17 147550.9
1117 123270.4 121673.91 124866.9
1118 125485.6 123820.87 127150.2
1119 103333.8 100683.52 105984.1
1120 121055.2 119483.52 122626.9
1121 133238.7 131074.54 135402.8
1122 152067.6 147984.91 156150.4
1123 127700.7 125929.40 129472.1
1124 129915.9 128005.94 131825.9
1125 114409.7 112649.49 116169.9
1126 122162.8 120584.36 123741.2
1127 127700.7 125929.40 129472.1
1128 149852.5 146015.95 153689.0
1129 135453.8 133097.22 137810.5
1130 138776.6 136106.60 141446.6
1131 121055.2 119483.52 122626.9
1132 135453.8 133097.22 137810.5
1133 127700.7 125929.40 129472.1
1134 123270.4 121673.91 124866.9
1135 136561.4 134103.22 139019.6
1136 118840.0 117247.67 120432.4
1137 128808.3 126971.25 130645.4
1138 125485.6 123820.87 127150.2
1139 143206.9 140087.16 146326.7
1140 126593.1 124879.55 128306.7
1141 114409.7 112649.49 116169.9
1142 112194.5 110298.32 114090.7
1143 152067.6 147984.91 156150.4
1144 155390.4 150933.57 159847.2
1145 122162.8 120584.36 123741.2
1146 115517.3 113813.26 117221.3
1147 116624.9 114968.06 118281.7
1148 138776.6 136106.60 141446.6
1149 115517.3 113813.26 117221.3
1150 121055.2 119483.52 122626.9
1151 116624.9 114968.06 118281.7
1152 137669.0 135106.23 140231.8
1153 133238.7 131074.54 135402.8
1154 118840.0 117247.67 120432.4
1155 132131.1 130056.88 134205.3
1156 127700.7 125929.40 129472.1
1157 124378.0 122752.56 126003.4
1158 136561.4 134103.22 139019.6
1159 127700.7 125929.40 129472.1
1160 121055.2 119483.52 122626.9
1161 101118.7  98247.92 103989.4
1162 119947.6 118371.26 121524.0
1163 123270.4 121673.91 124866.9
1164 124378.0 122752.56 126003.4
1165 107764.2 105523.20 110005.1
1166 126593.1 124879.55 128306.7
1167 121055.2 119483.52 122626.9
1168 122162.8 120584.36 123741.2
1169 131023.5 129034.23 133012.7
1170 126593.1 124879.55 128306.7
1171 121055.2 119483.52 122626.9
1172 123270.4 121673.91 124866.9
1173 123270.4 121673.91 124866.9
1174 139884.2 137104.62 142663.7
1175 119947.6 118371.26 121524.0
1176 134346.2 132087.81 136604.7
1177 121055.2 119483.52 122626.9
1178 105549.0 103109.52 107988.5
1179 119947.6 118371.26 121524.0
1180 127700.7 125929.40 129472.1
1181 124378.0 122752.56 126003.4
1182 115517.3 113813.26 117221.3
1183 117732.4 116113.09 119351.8
1184 115517.3 113813.26 117221.3
1185 127700.7 125929.40 129472.1
1186 148744.9 145030.32 152459.4
1187 123270.4 121673.91 124866.9
1188 117732.4 116113.09 119351.8
1189 134346.2 132087.81 136604.7
1190 115517.3 113813.26 117221.3
1191 138776.6 136106.60 141446.6
1192 111086.9 109112.55 113061.3
1193 125485.6 123820.87 127150.2
1194 118840.0 117247.67 120432.4
1195 109979.3 107921.00 112037.7
1196 114409.7 112649.49 116169.9
1197 139884.2 137104.62 142663.7
1198 131023.5 129034.23 133012.7
1199 116624.9 114968.06 118281.7
1200 119947.6 118371.26 121524.0
1201 109979.3 107921.00 112037.7
1202 114409.7 112649.49 116169.9
1203 122162.8 120584.36 123741.2
1204 116624.9 114968.06 118281.7
1205 125485.6 123820.87 127150.2
1206 129915.9 128005.94 131825.9
1207 128808.3 126971.25 130645.4
1208 137669.0 135106.23 140231.8
1209 122162.8 120584.36 123741.2
1210 117732.4 116113.09 119351.8
1211 116624.9 114968.06 118281.7
1212 119947.6 118371.26 121524.0
1213 114409.7 112649.49 116169.9
1214 119947.6 118371.26 121524.0
1215 125485.6 123820.87 127150.2
1216 122162.8 120584.36 123741.2
1217 122162.8 120584.36 123741.2
1218 122162.8 120584.36 123741.2
1219 139884.2 137104.62 142663.7
1220 118840.0 117247.67 120432.4
1221 137669.0 135106.23 140231.8
1222 109979.3 107921.00 112037.7
1223 118840.0 117247.67 120432.4
1224 137669.0 135106.23 140231.8
1225 117732.4 116113.09 119351.8
1226 116624.9 114968.06 118281.7
1227 124378.0 122752.56 126003.4
1228 139884.2 137104.62 142663.7
1229 118840.0 117247.67 120432.4
1230 122162.8 120584.36 123741.2
1231 112194.5 110298.32 114090.7
1232 108871.8 106724.35 111019.2
1233 121055.2 119483.52 122626.9
1234 121055.2 119483.52 122626.9
1235 119947.6 118371.26 121524.0
1236 104441.4 101897.87 106984.9
1237 113302.1 111477.56 115126.6
1238 147637.3 144043.83 151230.7
1239 131023.5 129034.23 133012.7
1240 143206.9 140087.16 146326.7
1241 114409.7 112649.49 116169.9
1242 138776.6 136106.60 141446.6
1243 109979.3 107921.00 112037.7
1244 128808.3 126971.25 130645.4
1245 118840.0 117247.67 120432.4
1246 105549.0 103109.52 107988.5
1247 127700.7 125929.40 129472.1
1248 123270.4 121673.91 124866.9
1249 113302.1 111477.56 115126.6
1250 129915.9 128005.94 131825.9
1251 113302.1 111477.56 115126.6
1252 129915.9 128005.94 131825.9
1253 123270.4 121673.91 124866.9
1254 109979.3 107921.00 112037.7
1255 139884.2 137104.62 142663.7
1256 128808.3 126971.25 130645.4
1257 117732.4 116113.09 119351.8
1258 138776.6 136106.60 141446.6
1259 109979.3 107921.00 112037.7
1260 123270.4 121673.91 124866.9
1261 133238.7 131074.54 135402.8
1262 109979.3 107921.00 112037.7
1263 121055.2 119483.52 122626.9
1264 121055.2 119483.52 122626.9
1265 144314.5 141078.17 147550.9
1266 115517.3 113813.26 117221.3
1267 131023.5 129034.23 133012.7
1268 125485.6 123820.87 127150.2
1269 104441.4 101897.87 106984.9
1270 132131.1 130056.88 134205.3
1271 119947.6 118371.26 121524.0
1272 115517.3 113813.26 117221.3
1273 137669.0 135106.23 140231.8
1274 104441.4 101897.87 106984.9
1275 134346.2 132087.81 136604.7
1276 134346.2 132087.81 136604.7
1277 156498.0 151915.39 161080.6
1278 131023.5 129034.23 133012.7
1279 119947.6 118371.26 121524.0
1280 105549.0 103109.52 107988.5
1281 129915.9 128005.94 131825.9
1282 138776.6 136106.60 141446.6
1283 134346.2 132087.81 136604.7
1284 117732.4 116113.09 119351.8
1285 119947.6 118371.26 121524.0
1286 152067.6 147984.91 156150.4
1287 145422.1 142067.86 148776.4
1288 107764.2 105523.20 110005.1
1289 125485.6 123820.87 127150.2
1290 135453.8 133097.22 137810.5
1291 115517.3 113813.26 117221.3
1292 132131.1 130056.88 134205.3
1293 132131.1 130056.88 134205.3
1294 135453.8 133097.22 137810.5
1295 113302.1 111477.56 115126.6
1296 122162.8 120584.36 123741.2
1297 117732.4 116113.09 119351.8
1298 159820.7 154858.21 164783.3
1299 119947.6 118371.26 121524.0
1300 125485.6 123820.87 127150.2
1301 111086.9 109112.55 113061.3
1302 148744.9 145030.32 152459.4
1303 113302.1 111477.56 115126.6
1304 117732.4 116113.09 119351.8
1305 143206.9 140087.16 146326.7
1306 111086.9 109112.55 113061.3
1307 105549.0 103109.52 107988.5
1308 102226.2  99466.78 104985.7
1309 112194.5 110298.32 114090.7
1310 107764.2 105523.20 110005.1
1311 111086.9 109112.55 113061.3
1312 114409.7 112649.49 116169.9
1313 109979.3 107921.00 112037.7
1314 109979.3 107921.00 112037.7
1315 106656.6 104318.10 108995.1
1316 112194.5 110298.32 114090.7
1317 155390.4 150933.57 159847.2
1318 111086.9 109112.55 113061.3
1319 116624.9 114968.06 118281.7
1320 107764.2 105523.20 110005.1
1321 112194.5 110298.32 114090.7
1322 134346.2 132087.81 136604.7
1323 116624.9 114968.06 118281.7
1324 108871.8 106724.35 111019.2
1325 144314.5 141078.17 147550.9
1326 112194.5 110298.32 114090.7
1327 107764.2 105523.20 110005.1
1328 108871.8 106724.35 111019.2
1329 115517.3 113813.26 117221.3
1330 117732.4 116113.09 119351.8
1331 136561.4 134103.22 139019.6
1332 145422.1 142067.86 148776.4
1333 111086.9 109112.55 113061.3
1334 134346.2 132087.81 136604.7
1335 105549.0 103109.52 107988.5
1336 125485.6 123820.87 127150.2
1337 116624.9 114968.06 118281.7
1338 108871.8 106724.35 111019.2
1339 111086.9 109112.55 113061.3
1340 111086.9 109112.55 113061.3
1341 106656.6 104318.10 108995.1
1342 116624.9 114968.06 118281.7
1343 108871.8 106724.35 111019.2
1344 132131.1 130056.88 134205.3
1345 104441.4 101897.87 106984.9
1346 113302.1 111477.56 115126.6
1347 115517.3 113813.26 117221.3
1348 109979.3 107921.00 112037.7
1349 106656.6 104318.10 108995.1
1350 123270.4 121673.91 124866.9
1351 119947.6 118371.26 121524.0
1352 111086.9 109112.55 113061.3
1353 105549.0 103109.52 107988.5
1354 138776.6 136106.60 141446.6
1355 102226.2  99466.78 104985.7
1356 106656.6 104318.10 108995.1
1357 127700.7 125929.40 129472.1
1358 111086.9 109112.55 113061.3
1359 124378.0 122752.56 126003.4
1360 136561.4 134103.22 139019.6
1361 121055.2 119483.52 122626.9
1362 108871.8 106724.35 111019.2
1363 111086.9 109112.55 113061.3
1364 114409.7 112649.49 116169.9
1365 105549.0 103109.52 107988.5
1366 111086.9 109112.55 113061.3
1367 115517.3 113813.26 117221.3
1368 113302.1 111477.56 115126.6
1369 118840.0 117247.67 120432.4
1370 117732.4 116113.09 119351.8
1371 109979.3 107921.00 112037.7
1372 121055.2 119483.52 122626.9
1373 109979.3 107921.00 112037.7
1374 124378.0 122752.56 126003.4
1375 129915.9 128005.94 131825.9
1376 132131.1 130056.88 134205.3
1377 115517.3 113813.26 117221.3
1378 109979.3 107921.00 112037.7
1379 105549.0 103109.52 107988.5
1380 134346.2 132087.81 136604.7
1381 111086.9 109112.55 113061.3
1382 114409.7 112649.49 116169.9
1383 111086.9 109112.55 113061.3
1384 121055.2 119483.52 122626.9
1385 115517.3 113813.26 117221.3
1386 104441.4 101897.87 106984.9
1387 109979.3 107921.00 112037.7
1388 107764.2 105523.20 110005.1
1389 113302.1 111477.56 115126.6
1390 116624.9 114968.06 118281.7
1391 131023.5 129034.23 133012.7
1392 145422.1 142067.86 148776.4
1393 108871.8 106724.35 111019.2
1394 155390.4 150933.57 159847.2
1395 139884.2 137104.62 142663.7
1396 107764.2 105523.20 110005.1
1397 103333.8 100683.52 105984.1
1398 159820.7 154858.21 164783.3
1399 115517.3 113813.26 117221.3
1400 111086.9 109112.55 113061.3
1401 121055.2 119483.52 122626.9
1402 108871.8 106724.35 111019.2
1403 126593.1 124879.55 128306.7
1404 114409.7 112649.49 116169.9
1405 116624.9 114968.06 118281.7
1406 113302.1 111477.56 115126.6
1407 111086.9 109112.55 113061.3
1408 116624.9 114968.06 118281.7
1409 108871.8 106724.35 111019.2
1410 107764.2 105523.20 110005.1
1411 150960.0 147000.78 154919.3
1412 127700.7 125929.40 129472.1
1413 105549.0 103109.52 107988.5
1414 132131.1 130056.88 134205.3
1415 107764.2 105523.20 110005.1
1416 114409.7 112649.49 116169.9
1417 129915.9 128005.94 131825.9
1418 108871.8 106724.35 111019.2
1419 111086.9 109112.55 113061.3
1420 111086.9 109112.55 113061.3
1421 118840.0 117247.67 120432.4
1422 101118.7  98247.92 103989.4
1423 108871.8 106724.35 111019.2
1424 104441.4 101897.87 106984.9
1425 109979.3 107921.00 112037.7
1426 111086.9 109112.55 113061.3
1427 108871.8 106724.35 111019.2
1428 114409.7 112649.49 116169.9
1429 154282.8 149951.24 158614.4
1430 108871.8 106724.35 111019.2
1431 128808.3 126971.25 130645.4
1432 119947.6 118371.26 121524.0
1433 158713.2 153877.68 163548.6
1434 119947.6 118371.26 121524.0
1435 109979.3 107921.00 112037.7
1436 113302.1 111477.56 115126.6
1437 105549.0 103109.52 107988.5
1438 109979.3 107921.00 112037.7
1439 121055.2 119483.52 122626.9
1440 119947.6 118371.26 121524.0
1441 112194.5 110298.32 114090.7
1442 107764.2 105523.20 110005.1
1443 118840.0 117247.67 120432.4
1444 108871.8 106724.35 111019.2
1445 140991.8 138100.58 143883.0
1446 132131.1 130056.88 134205.3
1447 127700.7 125929.40 129472.1
1448 131023.5 129034.23 133012.7
1449 134346.2 132087.81 136604.7
1450 104441.4 101897.87 106984.9
1451 115517.3 113813.26 117221.3
1452 119947.6 118371.26 121524.0
1453 121055.2 119483.52 122626.9
1454 116624.9 114968.06 118281.7
1455 109979.3 107921.00 112037.7
1456 118840.0 117247.67 120432.4
1457 153175.2 148968.37 157382.1
1458 136561.4 134103.22 139019.6
1459 124378.0 122752.56 126003.4
1460 138776.6 136106.60 141446.6
1461 121055.2 119483.52 122626.9
1462 113302.1 111477.56 115126.6
1463 121055.2 119483.52 122626.9
1464 121055.2 119483.52 122626.9
1465 111086.9 109112.55 113061.3
1466 121055.2 119483.52 122626.9
1467 109979.3 107921.00 112037.7
1468 144314.5 141078.17 147550.9
1469 111086.9 109112.55 113061.3
1470 145422.1 142067.86 148776.4
1471 111086.9 109112.55 113061.3
1472 135453.8 133097.22 137810.5
1473 128808.3 126971.25 130645.4
1474 131023.5 129034.23 133012.7
1475 111086.9 109112.55 113061.3
1476 118840.0 117247.67 120432.4
1477 104441.4 101897.87 106984.9
1478 140991.8 138100.58 143883.0
1479 128808.3 126971.25 130645.4
1480 108871.8 106724.35 111019.2
1481 144314.5 141078.17 147550.9
1482 109979.3 107921.00 112037.7
1483 114409.7 112649.49 116169.9
1484 145422.1 142067.86 148776.4
1485 108871.8 106724.35 111019.2
1486 106656.6 104318.10 108995.1
1487 105549.0 103109.52 107988.5
1488 104441.4 101897.87 106984.9
1489 103333.8 100683.52 105984.1
1490 105549.0 103109.52 107988.5
1491 111086.9 109112.55 113061.3
1492 107764.2 105523.20 110005.1
1493 106656.6 104318.10 108995.1
1494 109979.3 107921.00 112037.7
1495 112194.5 110298.32 114090.7
1496 152067.6 147984.91 156150.4
1497 109979.3 107921.00 112037.7
1498 115517.3 113813.26 117221.3
1499 112194.5 110298.32 114090.7
1500 108871.8 106724.35 111019.2
1501 135453.8 133097.22 137810.5
1502 117732.4 116113.09 119351.8
1503 111086.9 109112.55 113061.3
1504 146529.7 143056.37 150003.0
1505 112194.5 110298.32 114090.7
1506 107764.2 105523.20 110005.1
1507 109979.3 107921.00 112037.7
1508 117732.4 116113.09 119351.8
1509 122162.8 120584.36 123741.2
1510 132131.1 130056.88 134205.3
1511 149852.5 146015.95 153689.0
1512 109979.3 107921.00 112037.7
1513 135453.8 133097.22 137810.5
1514 108871.8 106724.35 111019.2
1515 122162.8 120584.36 123741.2
1516 115517.3 113813.26 117221.3
1517 108871.8 106724.35 111019.2
1518 104441.4 101897.87 106984.9
1519 111086.9 109112.55 113061.3
1520 113302.1 111477.56 115126.6
1521 114409.7 112649.49 116169.9
1522 109979.3 107921.00 112037.7
1523 125485.6 123820.87 127150.2
1524 106656.6 104318.10 108995.1
1525 115517.3 113813.26 117221.3
1526 113302.1 111477.56 115126.6
1527 105549.0 103109.52 107988.5
1528 109979.3 107921.00 112037.7
1529 124378.0 122752.56 126003.4
1530 119947.6 118371.26 121524.0
1531 109979.3 107921.00 112037.7
1532 112194.5 110298.32 114090.7
1533 143206.9 140087.16 146326.7
1534 105549.0 103109.52 107988.5
1535 109979.3 107921.00 112037.7
1536 126593.1 124879.55 128306.7
1537 113302.1 111477.56 115126.6
1538 127700.7 125929.40 129472.1
1539 136561.4 134103.22 139019.6
1540 117732.4 116113.09 119351.8
1541 112194.5 110298.32 114090.7
1542 111086.9 109112.55 113061.3
1543 111086.9 109112.55 113061.3
1544 112194.5 110298.32 114090.7
1545 107764.2 105523.20 110005.1
1546 112194.5 110298.32 114090.7
1547 116624.9 114968.06 118281.7
1548 116624.9 114968.06 118281.7
1549 114409.7 112649.49 116169.9
1550 113302.1 111477.56 115126.6
1551 122162.8 120584.36 123741.2
1552 107764.2 105523.20 110005.1
1553 121055.2 119483.52 122626.9
1554 125485.6 123820.87 127150.2
1555 137669.0 135106.23 140231.8
1556 117732.4 116113.09 119351.8
1557 115517.3 113813.26 117221.3
1558 113302.1 111477.56 115126.6
1559 134346.2 132087.81 136604.7
1560 108871.8 106724.35 111019.2
1561 112194.5 110298.32 114090.7
1562 106656.6 104318.10 108995.1
1563 116624.9 114968.06 118281.7
1564 118840.0 117247.67 120432.4
1565 106656.6 104318.10 108995.1
1566 108871.8 106724.35 111019.2
1567 108871.8 106724.35 111019.2
1568 111086.9 109112.55 113061.3
1569 113302.1 111477.56 115126.6
1570 132131.1 130056.88 134205.3
1571 148744.9 145030.32 152459.4
1572 108871.8 106724.35 111019.2
1573 155390.4 150933.57 159847.2
1574 135453.8 133097.22 137810.5
1575 104441.4 101897.87 106984.9
1576 102226.2  99466.78 104985.7
1577 155390.4 150933.57 159847.2
1578 115517.3 113813.26 117221.3
1579 111086.9 109112.55 113061.3
1580 122162.8 120584.36 123741.2
1581 111086.9 109112.55 113061.3
1582 121055.2 119483.52 122626.9
1583 107764.2 105523.20 110005.1
1584 115517.3 113813.26 117221.3
1585 113302.1 111477.56 115126.6
1586 112194.5 110298.32 114090.7
1587 118840.0 117247.67 120432.4
1588 109979.3 107921.00 112037.7
1589 104441.4 101897.87 106984.9
1590 150960.0 147000.78 154919.3
1591 123270.4 121673.91 124866.9
1592 103333.8 100683.52 105984.1
1593 129915.9 128005.94 131825.9
1594 115517.3 113813.26 117221.3
1595 117732.4 116113.09 119351.8
1596 135453.8 133097.22 137810.5
1597 109979.3 107921.00 112037.7
1598 112194.5 110298.32 114090.7
1599 114409.7 112649.49 116169.9
1600 121055.2 119483.52 122626.9
1601 111086.9 109112.55 113061.3
1602 106656.6 104318.10 108995.1
1603 115517.3 113813.26 117221.3
1604 111086.9 109112.55 113061.3
1605 108871.8 106724.35 111019.2
1606 106656.6 104318.10 108995.1
1607 111086.9 109112.55 113061.3
1608 123270.4 121673.91 124866.9
1609 129915.9 128005.94 131825.9
1610 127700.7 125929.40 129472.1
1611 108871.8 106724.35 111019.2
1612 125485.6 123820.87 127150.2
1613 107764.2 105523.20 110005.1
1614 124378.0 122752.56 126003.4
1615 107764.2 105523.20 110005.1
1616 136561.4 134103.22 139019.6
1617 112194.5 110298.32 114090.7
1618 121055.2 119483.52 122626.9
1619 121055.2 119483.52 122626.9
1620 125485.6 123820.87 127150.2
1621 115517.3 113813.26 117221.3
1622 111086.9 109112.55 113061.3
1623 119947.6 118371.26 121524.0
1624 137669.0 135106.23 140231.8
1625 109979.3 107921.00 112037.7
1626 117732.4 116113.09 119351.8
1627 111086.9 109112.55 113061.3
1628 123270.4 121673.91 124866.9
1629 114409.7 112649.49 116169.9
1630 112194.5 110298.32 114090.7
1631 106656.6 104318.10 108995.1
1632 106656.6 104318.10 108995.1
1633 109979.3 107921.00 112037.7
1634 104441.4 101897.87 106984.9
1635 121055.2 119483.52 122626.9
1636 107764.2 105523.20 110005.1
1637 126593.1 124879.55 128306.7
1638 127700.7 125929.40 129472.1
1639 111086.9 109112.55 113061.3
1640 125485.6 123820.87 127150.2
1641 118840.0 117247.67 120432.4
1642 125485.6 123820.87 127150.2
1643 117732.4 116113.09 119351.8
1644 135453.8 133097.22 137810.5
1645 112194.5 110298.32 114090.7
1646 109979.3 107921.00 112037.7
1647 125485.6 123820.87 127150.2
1648 133238.7 131074.54 135402.8
1649 126593.1 124879.55 128306.7
1650 113302.1 111477.56 115126.6
1651 122162.8 120584.36 123741.2
1652 115517.3 113813.26 117221.3
1653 119947.6 118371.26 121524.0
1654 119947.6 118371.26 121524.0
1655 113302.1 111477.56 115126.6
1656 122162.8 120584.36 123741.2
1657 122162.8 120584.36 123741.2
1658 109979.3 107921.00 112037.7
1659 112194.5 110298.32 114090.7
1660 106656.6 104318.10 108995.1
1661 123270.4 121673.91 124866.9
1662 114409.7 112649.49 116169.9
1663 131023.5 129034.23 133012.7
1664 107764.2 105523.20 110005.1
1665 119947.6 118371.26 121524.0
1666 126593.1 124879.55 128306.7
1667 114409.7 112649.49 116169.9
1668 114409.7 112649.49 116169.9
1669 109979.3 107921.00 112037.7
1670 108871.8 106724.35 111019.2
1671 106656.6 104318.10 108995.1
1672 111086.9 109112.55 113061.3
1673 109979.3 107921.00 112037.7
1674 108871.8 106724.35 111019.2
1675 111086.9 109112.55 113061.3
1676 127700.7 125929.40 129472.1
1677 119947.6 118371.26 121524.0
1678 108871.8 106724.35 111019.2
1679 109979.3 107921.00 112037.7
1680 123270.4 121673.91 124866.9
1681 112194.5 110298.32 114090.7
1682 117732.4 116113.09 119351.8
1683 125485.6 123820.87 127150.2
1684 106656.6 104318.10 108995.1
1685 108871.8 106724.35 111019.2
1686 112194.5 110298.32 114090.7
1687 126593.1 124879.55 128306.7
1688 136561.4 134103.22 139019.6
1689 106656.6 104318.10 108995.1
1690 109979.3 107921.00 112037.7
1691 105549.0 103109.52 107988.5
1692 122162.8 120584.36 123741.2
1693 123270.4 121673.91 124866.9
1694 105549.0 103109.52 107988.5
1695 114409.7 112649.49 116169.9
1696 123270.4 121673.91 124866.9
1697 121055.2 119483.52 122626.9
1698 126593.1 124879.55 128306.7
1699 113302.1 111477.56 115126.6
1700 115517.3 113813.26 117221.3
1701 115517.3 113813.26 117221.3
1702 104441.4 101897.87 106984.9
1703 116624.9 114968.06 118281.7
1704 119947.6 118371.26 121524.0
1705 113302.1 111477.56 115126.6
1706 118840.0 117247.67 120432.4
1707 123270.4 121673.91 124866.9
1708 117732.4 116113.09 119351.8
1709 112194.5 110298.32 114090.7
1710 112194.5 110298.32 114090.7
1711 104441.4 101897.87 106984.9
1712 113302.1 111477.56 115126.6
1713 109979.3 107921.00 112037.7
1714 125485.6 123820.87 127150.2
1715 108871.8 106724.35 111019.2
1716 103333.8 100683.52 105984.1
1717 106656.6 104318.10 108995.1
1718 111086.9 109112.55 113061.3
1719 121055.2 119483.52 122626.9
1720 108871.8 106724.35 111019.2
1721 108871.8 106724.35 111019.2
1722 118840.0 117247.67 120432.4
1723 107764.2 105523.20 110005.1
1724 121055.2 119483.52 122626.9
1725 125485.6 123820.87 127150.2
1726 124378.0 122752.56 126003.4
1727 127700.7 125929.40 129472.1
1728 119947.6 118371.26 121524.0
1729 111086.9 109112.55 113061.3
1730 111086.9 109112.55 113061.3
1731 106656.6 104318.10 108995.1
1732 116624.9 114968.06 118281.7
1733 112194.5 110298.32 114090.7
1734 105549.0 103109.52 107988.5
1735 115517.3 113813.26 117221.3
1736 105549.0 103109.52 107988.5
1737 106656.6 104318.10 108995.1
1738 119947.6 118371.26 121524.0
1739 109979.3 107921.00 112037.7
1740 112194.5 110298.32 114090.7
1741 140991.8 138100.58 143883.0
1742 135453.8 133097.22 137810.5
1743 123270.4 121673.91 124866.9
1744 133238.7 131074.54 135402.8
1745 135453.8 133097.22 137810.5
1746 114409.7 112649.49 116169.9
1747 116624.9 114968.06 118281.7
1748 107764.2 105523.20 110005.1
1749 108871.8 106724.35 111019.2
1750 117732.4 116113.09 119351.8
1751 118840.0 117247.67 120432.4
1752 107764.2 105523.20 110005.1
1753 121055.2 119483.52 122626.9
1754 126593.1 124879.55 128306.7
1755 117732.4 116113.09 119351.8
1756 109979.3 107921.00 112037.7
1757 121055.2 119483.52 122626.9
1758 119947.6 118371.26 121524.0
1759 113302.1 111477.56 115126.6
1760 109979.3 107921.00 112037.7
1761 115517.3 113813.26 117221.3
1762 109979.3 107921.00 112037.7
1763 133238.7 131074.54 135402.8
1764 103333.8 100683.52 105984.1
1765 131023.5 129034.23 133012.7
1766 121055.2 119483.52 122626.9
1767 115517.3 113813.26 117221.3
1768 126593.1 124879.55 128306.7
1769 115517.3 113813.26 117221.3
1770 111086.9 109112.55 113061.3
1771 116624.9 114968.06 118281.7
1772 128808.3 126971.25 130645.4
1773 116624.9 114968.06 118281.7
1774 113302.1 111477.56 115126.6
1775 122162.8 120584.36 123741.2
1776 119947.6 118371.26 121524.0
1777 106656.6 104318.10 108995.1
1778 125485.6 123820.87 127150.2
1779 109979.3 107921.00 112037.7
1780 112194.5 110298.32 114090.7
1781 125485.6 123820.87 127150.2
1782 109979.3 107921.00 112037.7
1783 106656.6 104318.10 108995.1
1784 109979.3 107921.00 112037.7
1785 109979.3 107921.00 112037.7
1786 135453.8 133097.22 137810.5
1787 109979.3 107921.00 112037.7
1788 119947.6 118371.26 121524.0
1789 107764.2 105523.20 110005.1
1790 132131.1 130056.88 134205.3
1791 109979.3 107921.00 112037.7
1792 133238.7 131074.54 135402.8
1793 111086.9 109112.55 113061.3
1794 126593.1 124879.55 128306.7
1795 113302.1 111477.56 115126.6
1796 112194.5 110298.32 114090.7
1797 117732.4 116113.09 119351.8
1798 136561.4 134103.22 139019.6
1799 116624.9 114968.06 118281.7
1800 115517.3 113813.26 117221.3
1801 138776.6 136106.60 141446.6
1802 139884.2 137104.62 142663.7
1803 118840.0 117247.67 120432.4
1804 105549.0 103109.52 107988.5
1805 117732.4 116113.09 119351.8
1806 116624.9 114968.06 118281.7
1807 131023.5 129034.23 133012.7
1808 108871.8 106724.35 111019.2
1809 126593.1 124879.55 128306.7
1810 121055.2 119483.52 122626.9
1811 111086.9 109112.55 113061.3
1812 125485.6 123820.87 127150.2
1813 122162.8 120584.36 123741.2
1814 119947.6 118371.26 121524.0
1815 118840.0 117247.67 120432.4
1816 112194.5 110298.32 114090.7
1817 129915.9 128005.94 131825.9
1818 111086.9 109112.55 113061.3
1819 136561.4 134103.22 139019.6
1820 101118.7  98247.92 103989.4
1821 108871.8 106724.35 111019.2
1822 125485.6 123820.87 127150.2
1823 112194.5 110298.32 114090.7
1824 106656.6 104318.10 108995.1
1825 119947.6 118371.26 121524.0
1826 112194.5 110298.32 114090.7
1827 106656.6 104318.10 108995.1
1828 118840.0 117247.67 120432.4
1829 113302.1 111477.56 115126.6
1830 119947.6 118371.26 121524.0
1831 116624.9 114968.06 118281.7
1832 132131.1 130056.88 134205.3
1833 111086.9 109112.55 113061.3
1834 108871.8 106724.35 111019.2
1835 111086.9 109112.55 113061.3
1836 107764.2 105523.20 110005.1
1837 117732.4 116113.09 119351.8
1838 107764.2 105523.20 110005.1
1839 112194.5 110298.32 114090.7
1840 119947.6 118371.26 121524.0
1841 114409.7 112649.49 116169.9
1842 128808.3 126971.25 130645.4
1843 104441.4 101897.87 106984.9
1844 107764.2 105523.20 110005.1
1845 118840.0 117247.67 120432.4
1846 109979.3 107921.00 112037.7
1847 122162.8 120584.36 123741.2
1848 116624.9 114968.06 118281.7
1849 117732.4 116113.09 119351.8
1850 112194.5 110298.32 114090.7
1851 114409.7 112649.49 116169.9
1852 109979.3 107921.00 112037.7
1853 108871.8 106724.35 111019.2
1854 117732.4 116113.09 119351.8
1855 114409.7 112649.49 116169.9
1856 109979.3 107921.00 112037.7
1857 106656.6 104318.10 108995.1
1858 108871.8 106724.35 111019.2
1859 125485.6 123820.87 127150.2
1860 132131.1 130056.88 134205.3
1861 128808.3 126971.25 130645.4
1862 105549.0 103109.52 107988.5
1863 124378.0 122752.56 126003.4
1864 111086.9 109112.55 113061.3
1865 125485.6 123820.87 127150.2
1866 107764.2 105523.20 110005.1
1867 138776.6 136106.60 141446.6
1868 114409.7 112649.49 116169.9
1869 118840.0 117247.67 120432.4
1870 123270.4 121673.91 124866.9
1871 124378.0 122752.56 126003.4
1872 113302.1 111477.56 115126.6
1873 108871.8 106724.35 111019.2
1874 119947.6 118371.26 121524.0
1875 139884.2 137104.62 142663.7
1876 109979.3 107921.00 112037.7
1877 117732.4 116113.09 119351.8
1878 113302.1 111477.56 115126.6
1879 124378.0 122752.56 126003.4
1880 113302.1 111477.56 115126.6
1881 109979.3 107921.00 112037.7
1882 107764.2 105523.20 110005.1
1883 104441.4 101897.87 106984.9
1884 109979.3 107921.00 112037.7
1885 103333.8 100683.52 105984.1
1886 119947.6 118371.26 121524.0
1887 107764.2 105523.20 110005.1
1888 125485.6 123820.87 127150.2
1889 129915.9 128005.94 131825.9
1890 113302.1 111477.56 115126.6
1891 124378.0 122752.56 126003.4
1892 119947.6 118371.26 121524.0
1893 127700.7 125929.40 129472.1
1894 116624.9 114968.06 118281.7
1895 134346.2 132087.81 136604.7
1896 109979.3 107921.00 112037.7
1897 109979.3 107921.00 112037.7
1898 127700.7 125929.40 129472.1
1899 134346.2 132087.81 136604.7
1900 127700.7 125929.40 129472.1
1901 111086.9 109112.55 113061.3
1902 122162.8 120584.36 123741.2
1903 117732.4 116113.09 119351.8
1904 117732.4 116113.09 119351.8
1905 122162.8 120584.36 123741.2
1906 115517.3 113813.26 117221.3
1907 124378.0 122752.56 126003.4
1908 125485.6 123820.87 127150.2
1909 112194.5 110298.32 114090.7
1910 109979.3 107921.00 112037.7
1911 107764.2 105523.20 110005.1
1912 125485.6 123820.87 127150.2
1913 113302.1 111477.56 115126.6
1914 128808.3 126971.25 130645.4
1915 106656.6 104318.10 108995.1
1916 118840.0 117247.67 120432.4
1917 127700.7 125929.40 129472.1
1918 117732.4 116113.09 119351.8
1919 116624.9 114968.06 118281.7
1920 109979.3 107921.00 112037.7
1921 106656.6 104318.10 108995.1
1922 109979.3 107921.00 112037.7
1923 111086.9 109112.55 113061.3
1924 107764.2 105523.20 110005.1
1925 111086.9 109112.55 113061.3
1926 109979.3 107921.00 112037.7
1927 127700.7 125929.40 129472.1
1928 122162.8 120584.36 123741.2
1929 109979.3 107921.00 112037.7
1930 107764.2 105523.20 110005.1
1931 124378.0 122752.56 126003.4
1932 109979.3 107921.00 112037.7
1933 119947.6 118371.26 121524.0
1934 123270.4 121673.91 124866.9
1935 107764.2 105523.20 110005.1
1936 109979.3 107921.00 112037.7
1937 108871.8 106724.35 111019.2
1938 125485.6 123820.87 127150.2
1939 134346.2 132087.81 136604.7
1940 105549.0 103109.52 107988.5
1941 108871.8 106724.35 111019.2
1942 107764.2 105523.20 110005.1
1943 124378.0 122752.56 126003.4
1944 124378.0 122752.56 126003.4
1945 104441.4 101897.87 106984.9
1946 111086.9 109112.55 113061.3
1947 125485.6 123820.87 127150.2
1948 122162.8 120584.36 123741.2
1949 127700.7 125929.40 129472.1
1950 115517.3 113813.26 117221.3
1951 115517.3 113813.26 117221.3
1952 114409.7 112649.49 116169.9
1953 106656.6 104318.10 108995.1
1954 117732.4 116113.09 119351.8
1955 122162.8 120584.36 123741.2
1956 113302.1 111477.56 115126.6
1957 115517.3 113813.26 117221.3
1958 124378.0 122752.56 126003.4
1959 117732.4 116113.09 119351.8
1960 109979.3 107921.00 112037.7
1961 111086.9 109112.55 113061.3
1962 103333.8 100683.52 105984.1
1963 111086.9 109112.55 113061.3
1964 109979.3 107921.00 112037.7
1965 125485.6 123820.87 127150.2
1966 107764.2 105523.20 110005.1
1967 105549.0 103109.52 107988.5
1968 107764.2 105523.20 110005.1
1969 111086.9 109112.55 113061.3
1970 119947.6 118371.26 121524.0
1971 111086.9 109112.55 113061.3
1972 108871.8 106724.35 111019.2
1973 118840.0 117247.67 120432.4
1974 107764.2 105523.20 110005.1
1975 118840.0 117247.67 120432.4
1976 127700.7 125929.40 129472.1
1977 123270.4 121673.91 124866.9
1978 127700.7 125929.40 129472.1
1979 119947.6 118371.26 121524.0
1980 111086.9 109112.55 113061.3
1981 108871.8 106724.35 111019.2
1982 106656.6 104318.10 108995.1
1983 118840.0 117247.67 120432.4
1984 112194.5 110298.32 114090.7
1985 104441.4 101897.87 106984.9
1986 116624.9 114968.06 118281.7
1987 104441.4 101897.87 106984.9
1988 108871.8 106724.35 111019.2
1989 119947.6 118371.26 121524.0
1990 108871.8 106724.35 111019.2
1991 115517.3 113813.26 117221.3
1992 140991.8 138100.58 143883.0
1993 137669.0 135106.23 140231.8
1994 123270.4 121673.91 124866.9
1995 131023.5 129034.23 133012.7
1996 133238.7 131074.54 135402.8
1997 111086.9 109112.55 113061.3
1998 115517.3 113813.26 117221.3
1999 107764.2 105523.20 110005.1
2000 108871.8 106724.35 111019.2</code></pre>
</div>
</div>
<p>These are the confidence intervals for the predicted values of salary for all 2000 datapoints in my original population. These ranges are rather tight and it is interesting to note that almost all these predictions are around 100,000 USD, which makes sense given that the mean is 120,954.40 USD.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>dp <span class="ot">&lt;-</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(population, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> Income)) <span class="sc">+</span> </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"lightblue"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>dp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats-3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><u>Multi-linear Regression</u></p>
<p>While this dataset only has 2 quantitative variables, I want to show that I can conduct a multi-linear regression, so solely for the purpose of demonstration I am going to create two fake variables: number of children and weight. Obviously, in a real-world dataset doing this would be entirely problematic, so I cannot emphasis more that this is just for demonstration.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sorts data by income</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> population[<span class="fu">order</span>(population<span class="sc">$</span>Income), ]</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># find halfway point of data</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(population)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>half <span class="ot">&lt;-</span> n <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign 0–3 to the bottom 50% (lower income group)</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>population<span class="sc">$</span>number_of_children <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>population<span class="sc">$</span>number_of_children[<span class="dv">1</span><span class="sc">:</span>half] <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">size =</span> half, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign 3–5 to the top 50% (higher income group)</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>population<span class="sc">$</span>number_of_children[(half <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>n] <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">size =</span> half, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a><span class="co"># creates weight randomly generated</span></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>population<span class="sc">$</span>weight <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">47</span><span class="sc">:</span><span class="dv">77</span>, <span class="at">size =</span> <span class="dv">2000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now with 4 quantitative variables, I can run a multi-linear regression. Let’s see if there are patterns between Income and Age, number of children, or weight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Income <span class="sc">~</span> Age <span class="sc">+</span> number_of_children <span class="sc">+</span> weight, <span class="at">data =</span> population)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Income ~ Age + number_of_children + weight, data = population)

Residuals:
   Min     1Q Median     3Q    Max 
-85328 -18832  -3276  14499 168279 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        64637.82    5209.17  12.408   &lt;2e-16 ***
Age                  706.23      59.42  11.885   &lt;2e-16 ***
number_of_children 12443.87     437.27  28.458   &lt;2e-16 ***
weight               -51.72      75.70  -0.683    0.495    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30240 on 1996 degrees of freedom
Multiple R-squared:  0.3714,    Adjusted R-squared:  0.3705 
F-statistic: 393.2 on 3 and 1996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Here we can see that Age and number of children have a p-value of &lt;2e-16, so they are statistically significant. Let’s drop weight since it is not statistically significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>newmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Age <span class="sc">+</span> number_of_children, <span class="at">data =</span> population)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(newmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Income ~ Age + number_of_children, data = population)

Residuals:
   Min     1Q Median     3Q    Max 
-84996 -18856  -3413  14488 168253 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         61440.3     2287.0   26.86   &lt;2e-16 ***
Age                   705.4       59.4   11.88   &lt;2e-16 ***
number_of_children  12448.3      437.2   28.48   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30230 on 1997 degrees of freedom
Multiple R-squared:  0.3713,    Adjusted R-squared:  0.3707 
F-statistic: 589.7 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Age and Number of Children are still statistically relevant even when weight is removed. When age and number of children is zero, Income is 62,660 USD, which here is not relevant because minimum age is 18 (and realistically people are not born earning money). It is interesting to note it is significantly smaller than the previous model’s intercept (81,182.10 USD).</p>
<p>For every 1 unit increase in Age, Income increases by 692.95 USD, holding the number of children constant. For every 1 unit increase in number of children with age held constant, Income increases by 12,193.83 USD.</p>
<p>Based on the residual standard error, we can see that the predictions deviate from actual income by 30,590 USD. The model only explains 35.56% of the variation in income. This is a huge improvement of the previous model, since Age vs Income only explained 11.6% of the variation.</p>
<p>We can formally compare the models using an ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Simple regression</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Age, <span class="at">data =</span> population)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Multiple regression</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Age <span class="sc">+</span> number_of_children, <span class="at">data =</span> population)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Income ~ Age
Model 2: Income ~ Age + number_of_children
  Res.Df        RSS Df  Sum of Sq      F    Pr(&gt;F)    
1   1998 2.5663e+12                                   
2   1997 1.8252e+12  1 7.4108e+11 810.82 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The residual sum of squares drops from 2.5663e+12 to 1.8688e+12 when adding number of children. This means the reduction in error is highly significant, confirming that adding number_of_children significantly improves the model fit beyond what age could explain.</p>
<section id="addendum-1" class="level5">
<h5 class="anchored" data-anchor-id="addendum-1">Addendum 1:</h5>
<p>I used some descriptive statistical tools in this assignment: I looked at mean, max, min, and boxplots. Mean is the average of a dataset - all points are added together and then divided by the total number of observations. Max is the highest number in a set of observations. Min is the lowest number in a set of observations. A boxplot visualizes the median, spread, and outliers of a numerical variable.</p>
<p>For qualitative analysis, I used hypothesis testing, balloon plots, chi squared testing and cramers V. Hypothesis testing is a tool to make inferences about a population by examining a sample of its data. The null hypothesis always assumes the default, whereas the alternative hypothesis tests the idea you want to validate. The balloon plot is a visualization tool that uses circles in a grid. The size of the balloon is proportional to the value it represents, and can compare sizes across different categories. Chi Square test makes claims about proportions in categorical data. It is a type of test that can be used with hypothesis testing to determine inference. The Cramer’s V test, used in conjunction with the Chi Square test, measures the association of the two variables between 0-1, with 1 representing a perfect association.</p>
<p>For the first quantitative analysis, I used a simple linear regression. A simple linear regression studies the correlation between one independent variable (X) and it dependent variable (Y). It finds a linear relationship between the two variables and fits a ‘best-fit’ straight line across the data. The space between the actual value and the predicted value is called a ‘residual’. A simple linear regression assumes a linear relationship, homogeneity (that the errors have a mean of zero), homoscedasticity (that the variance of the errors is constant), independence of the errors (one observation doesn’t imply anything about the other), and normality (that the errors follow a normal distribution). To check these assumptions, I conducted residual analysis. I also used the simple linear model to predict observations (later combined with confidence intervals to give a range of the predicted observation) and compared predicted and actual values to evaluate the model.</p>
<p>For the second analysis, I used a multi-linear regression looking at the relationship of indepdent variables age, number of children, and weight on dependent variable income. A multi-linear regression is different from a simple linear regression because it looks at more than one independent variable. After building and evaluation the model, I compared the first linear model with the second multi-linear model using an ANOVA test, which evaluates variance between two groups.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>